SPLURT-Station/S.P.L.U.R.T-Station-13

code/datums/mind.dm, code/modules/antagonists/traitor/classes/human.dm, modular_eros/code/game/gamemodes/objectives.dm, modular_eros/code/modules/jobs/job_types/prisoner.dm, tgstation.dme
Title.
More unique shit.
Your mother.
:cl:
add: Tots have a "Rescue Prisoner" objective now
/:cl:
=> [SEMI-MODULAR] Prisoner Rescue Objective

modular_sand/code/modules/jobs/job_types/_job_alt_titles.dm
New "Blacksmith" alt job title added to assistant.
Quite a sounding job title for those who want to do blacksmithing at the station. Plus, it's a pretty good reason to bother the cargo department with ordering a normal anvil.
No
:cl: DrNukesky
add: Added new job title
/:cl:
=> New job title for assistant

code/modules/mob/living/carbon/human/species_types/synths.dm
=> speedmerge

modular_eros/code/game/object/items/stacks/sheets/sheet_types.dm, modular_sand/code/modules/jobs/job_types/_job_alt_titles.dm
=> Alt titles

code/modules/mob/living/carbon/examine.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/simple_animal/hostile/space_dragon.dm
fixes heat quirk + spess dragoon
fixes heat quirk + spess dragoon
pipebomb in your mailbox
🆑 
fix: fixes heat quirk + spess dragoon
/:cl:
=> fixes heat quirk + spess dragoon

modular_sand/code/datums/interactions/lewd/_lewd_extra.dm, modular_sand/code/datums/interactions/lewd/lewd_datums_extra.dm
Self suck interactions in the interactions menu
flapping isn't enough, something you gotta go full deepthroat on yourself
No
:cl:
add: Added self suck interactions
/:cl:
=> Autostuff 2

code/game/objects/effects/decals/cleanable.dm, code/game/objects/effects/decals/cleanable/humans.dm, code/modules/antagonists/cult/blood_magic.dm, code/modules/mob/living/carbon/human/human_movement.dm
checking if it's the correct type should be done for all procs that require shoes to be of type /obj/item/clothing/shoes
temp fix while it gets merged on upstream or something
i hate crashes
No
:cl:
fix: fixes part of the shoe errors
/:cl:
=> Fixes some of the new size system's runtimes

modular_sand/code/datums/components/crafting/recipes/recipes_misc.dm
Love is no longer in the air, I guess
lol
more like the opposite
:cl:
fix: the crafting menu should be working now
/:cl:
=> Fixes broken crafting menu

code/game/objects/buckling.dm
Just like TG!
having to be in the same turf is rather annoying sometimes
no
:cl:
tweak: You can now buckle yourself to seats 1 turf away
/:cl:
=> You can now buckle yourself to seats 1 turf away

code/modules/client/preferences.dm
=> preference naming update

tgstation.dme
Currently just fixes D.A.B. helmet still being under assistant restriction (loadout helmet changes wasn't ticked), thanks VSCode.
It shall allow further additions/tweaks for head loadout items to work, instead of adding something and for some reason it doesn't show up.
None, its a quick fix.
=> Ticks head loadout changes

modular_splurt/code/modules/research/designs/biogenerator_designs.dm, tgstation.dme
these are cool i think
adds some new designs to the biogenerator (?)
admeme asked me to so there's more food I think
probably
:cl:
add: Added extra food biogenerator designs
/:cl:
=> new biogenerator designs

_maps/templates/hilbertshotel.dmm
Hilbert's Hotel would run out of air after a few hours of typefucking, so there is now a way to replenish air supply alongside a scenery update, and the addition of Kinkmate vendors and a stripper pole. There is a paper on the counter detailing the update for players.
it probably isnt because half the station wont be on manifest kekw
Tweak: adds air canisters, portable scrubber, kinkmate and stripper pole to Hilbert's: Retardee
=> Hilbert's Hotel Update

_maps/shuttles/whiteship_meta.dmm
The NTSS Evergreen was a salvage ship, pulling in old wrecks to reclaim fine material to sell at port. One day it never returned. It was a vessel with a small crew, so it may have been an innocent accident, but some suspect sabotague, or an inside job.
Makes the location more cool and tells a story.
🆑 
tweak: Whiteship has cult archives, forge, several runed metal, ritual dagger, several pylons, two shades and four constructs added, with some maint loot spawners reduced and slight edits to interior and exterior hull.
/🆑
=> NTSS Evergreen - Whiteship, MetaStation

_maps/templates/hilbertshotel.dmm
Muh lightbulb rightsss
just removes a lightbulb kekw
idc
:cl:
tweak: MY LIGHTBULB REMOVAL!!!!!!
/:cl:
=> Literally just removes a lightbulb lmao

modular_splurt/code/datums/interactions/lewd/_lewd.dm, modular_splurt/code/modules/mob/eros_emotes.dm
Probably lots of people are gonna be happy about this
Now you can't hear brap noises unless you have the unholy option on
you tell me
no
:cl:
sounddel: Now you can't hear brap noises if you set unholy to "No"
/:cl:
=> rip in brap

config/config.txt, config/splurt/fetish_content.txt, modular_sand/code/datums/elements/holder_micro.dm, modular_splurt/code/controllers/configuration/entries/splurt_fetish_content.dm, tgstation.dme
ghghghgjglgngbg
This makes it so that you can configure what the max ratio between the person being picked up/whoever's picking them up can be or deactivate it as a whole. Tell me if you wanna use this config entry for anything else
this way you can configure and control it more easily depending on what you want for your station ig
No
:cl:
config: made he maximum ratio for picking up people a config
/:cl:
=> now its a config

code/modules/jobs/job_types/captain.dm, code/modules/jobs/job_types/chief_engineer.dm, code/modules/jobs/job_types/chief_medical_officer.dm, code/modules/jobs/job_types/head_of_personnel.dm, code/modules/jobs/job_types/head_of_security.dm, code/modules/jobs/job_types/prisoner.dm, code/modules/jobs/job_types/quartermaster.dm, code/modules/jobs/job_types/research_director.dm
Adds descriptions based on the discord rules for each command role + prisoner. I've tested it all in local.
It's good for the game because it harder to forget the specific rules for all our 6 command roles.
No
:cl:
add: Rule flavour texts for each command role upon joining the server.
/:cl:
=> Command flavour texts

code/modules/vending/kinkmate.dm, modular_sand/code/game/objects/items/lewd_items/leash.dm, modular_sand/code/game/objects/items/storage/belt.dm
tfw seggsclaws give you a better understanding of things
ports (or more like uncomments lol) leashes from hyper, they work now!
Mmm pet
yeafl
:cl:
add: leashes!!!! they can be crafted and taken from kinkmates and slutbelts
/:cl:
=> Leashes actually work now

code/game/machinery/computer/medical.dm
=> Fixes a href exploit

modular_sand/code/datums/interactions/lewd/_lewd.dm, modular_sand/code/datums/interactions/lewd/lewd_datums.dm, modular_sand/code/datums/interactions/lewd/lewd_datums_extra.dm, modular_splurt/code/datums/interactions/lewd/lewd_datums.dm
Throatfucking was meant to do damage but you can spam it for 10 minutes and the partner would be completely fine. Now it does damage > : )
Adds logging data to ERP verbs so it should actually say what happened instead of 'X ass-slapped Y'
:cl:
tweak: Throat fucking now actually does (noticeable) oxy damage
fix: Erp verb logging (for admins) should now be accurate.
/:cl:
=> Lewd fixes

code/datums/components/crafting/crafting.dm, code/game/objects/items/devices/transfer_valve.dm, code/modules/atmospherics/machinery/portable/canister.dm, code/modules/reagents/chemistry/machinery/chem_dispenser.dm, modular_splurt/code/modules/admin/playtimes.dm, tgui/packages/tgui/interfaces/PlayerPlaytimes.js
Adds a warning for if a player crafts an IED or Molotov Cocktail.
Optimises code and panel JS to make adding future warnings easier.
:cl:
add: More admin grief warnings
/:cl:
=> Grief Warning - Crafting

_maps/splurt_maps/templates/hilbertshotel.dmm, modular_splurt/code/modules/ruins/spaceruin_code/hilbertshotel.dm, tgstation.dme
This adds an actual atmos system to the hotel rooms. Map edited by Shikari (ty!)
Getting oxy damage without being throatfugged is not one of my kinks
no
:cl: Yoichi.boy
fix: Hilbert's shouldn't suddenly run out of air from now on
/:cl:
=> now I can properly pollute hotel's rooms with my f-

code/modules/client/preferences.dm
Adds three spans to the character preferences menu with short explanation tooltips for the unholy, extreme and harmful verb options. 
Makes it obvious what these toggles do and doesn't crowd the UI as much as including them inline with the rest of the text.
No.
:cl:
add: explanations for unholy verb, extreme verb and harmful verb toggles in preferences.
/:cl:
=> Add explanations for verb toggles in preferences

code/modules/ruins/spaceruin_code/hilbertshotel.dm
=> Fixes Hilbert Deleting

modular_splurt/code/modules/vending/kinkmate.dm
Title. Fulfills suggestion 294
Easier access to MELK
Working on a port...? I guess...?
:cl:
tweak: Milking machines can now be found in kinkmates
/:cl:
=> Adds milking machines to kinkmates (Suggestion #294)

modular_splurt/code/datums/interactions/lewd/_lewd.dm, modular_splurt/code/datums/interactions/lewd/lewd_datums.dm
Adds a (very fun) pp lewding interaction
I forgot I was gonna add it later lol
:cl:
add: added urethral penetration interactions
/:cl:
=> nothing to see here

code/modules/integrated_electronics/core/printer.dm, modular_splurt/code/modules/admin/playtimes.dm
Adds an admin warning when a new player uses circuits.
:cl:
add: Another admin grief tool
/:cl:
=> Anti-Grief: Circuits

modular_splurt/_maps/RandomRuins/LavaRuins/lavaland_surface_abandoned_shelter.dmm
Just a few changing to an lava land hermit ruin after the ability to construct R&D boards in crafting removed and fix an occurring problem with the airlock entrance's tile.
It to keep it updated to the server while still having it be as intended.
No
:cl:777joshua777
add: Added more things
del: Removed old things
fix: fixed a few things
/:cl:
=> Wandering Hermit Tidying up/changes

modular_splurt/code/modules/admin/playtimes.dm, modular_splurt/code/modules/client/client_procs.dm, tgstation.dme
Adds an icon on the player playtimes UI if the player is likely to be using a Proxy/VPN
Will help to keep possible ban evaders in check
No
:cl:
admin: Adds a vpn detection icon to the player playtimes
/:cl:
=> IP intel for playtimes

_maps/RandomRuins/StationRuins/Box/Engine/engine_nuke.dmm
=> Adds the boxstation RBMK reactor

modular_splurt/code/modules/client/loadout/suit.dm, modular_splurt/code/modules/client/loadout/uniform.dm
Completes the wishes of a number of different suggestions - which is a good start towards actually DOING suggestions here. All of them were simple additions to the loadout menu, which are stupidly easy to do, thankfully.
- Suggestion \# 148
- Suggestion \# 151
- Suggestion \# 183
Increases user retention when they're actually being heard.
Nah
:cl:
add: Added draculas coat, waiter's uniform and techpriest's robes to the loadout menu.
/:cl:
=> lewdout items

modular_sand/code/datums/interactions/interaction_interface.dm, modular_sand/code/datums/interactions/lewd/_lewd.dm
Allows interactions with them big ole orbs on borgs.
Borgs need nut love too!
:cl:
code: changed some code
/:cl:
=> [Minor pull] Give borgs balls!

_maps/map_files/CogStation/CogStation.dmm
Removes the fucking door so it acts like the goddamn Boxstation TEG
This is so it stops the fucking bullshit ass greytide plasma flood
:cl:
add: Added walls to the incin to prevent access
del: Removed airlock to incin
edit: moved the pipe over one tile
/:cl:
=> Update the incin for the Cogstation TEG

modular_splurt/code/game/object/items/storage/secure.dm, modular_splurt/code/game/object/structures/crates_lockers/closets/secure/security.dm, modular_splurt/code/modules/cargo/packs/armory.dm
Due to the Enforcer .45's mistreatment by the Captain, the Captain is loosing round start access to the Enforcer .45. 
Several captain's have used the Enforcer for its lethal ammo out of box. This is my attempt to slow that down as you still have the Egun.
No a fix
:cl: radar651
add: A note to the Captain's locker
del: Removed the Captain's enforcer from the Captain's locker
tweak: Moved the Captain's enforcer to the Cargo ordering system like the Captain's Pen. Can be bought for 6k.
/:cl:
=> Moving of the Captain's Enforcer

_maps/map_files/BoxStation/BoxStation.dmm
:cl:
add: Added power cables to Tcomms SMES
/:cl:
=> Fixes tcomms power issue

modular_splurt/code/modules/mob/splurt_emotes.dm
and so do pretty much every other carbon race that couldn't laugh yet
Title
If anyone wants to make a better system for the laugh emote or change the audio file for a certain race please go ahead.
\>:3
No
:cl:
tweak: Now anthros and other races can audibly laugh
/:cl:
=> Now anthros can laugh

_maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/KiloStation/KiloStation.dmm, _maps/map_files/MetaStation/MetaStation.dmm
I don't know who the fuck didn't add goddamn wires to the tcomms and AI sat but I will find them and make them in to a power cable
:cl:
add: Added wiring to meta
add: Added wiring to kilo
add Added wiring to delta
/:cl:
=> Fix further Wiring issues

_maps/map_files/Deltastation/DeltaStation2.dmm
Alice is a femboy slut and needs to be destroyed
:cl:
fix: Fixed the blueshield office vents
/:cl:
=> Fixes delta blueshield office vents

modular_splurt/code/modules/cargo/bounties/lewd.dm
Replaced the Bruhnaris typo to Nanotrasen for the High-Prioritized Milk Cargo Bounty, from the Pull #232 
Screw your Keknaris faction, Winfre.
From Hyper, fixed just a typo.
:cl:
fix: spellcheck: fixed a bounty typo with the high-prioritized milk reward.
/:cl:
=> [Modular]Fixing a typo with the High-Prioritized Milk Bounty.

code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
Yeah so I goofed. This should fix the modular drinks thing. The icon wasn't reverting when the glass was empty so now it'll actually do that. I should probably test things more...
You can now fully drink your cum chalice, you slut.
NOPE.
:cl:
fix: Drinks no longer go invisible when they're a modular icon file and get emptied
/:cl:
=> Fixes modular drink icons disappearing

code/modules/cargo/export_scanner.dm, modular_splurt/code/modules/cargo/packs/goodies.dm
webedit
:cl:
spellcheck: export scanner description, switch blade order
/:cl:
=> fixes typos ig 

modular_splurt/code/modules/client/verbs/looc.dm, modular_splurt/code/modules/client/verbs/ooc.dm, tgstation.dme
literally 1987
This makes it so that you can't use ooc nor looc either if you haven't linked your discord
If you've been on the server the last two rounds you'll know why
No
:cl:
tweak: Now you need to have your discord linked to use ooc and looc too
/:cl:
=> yet another 1984 pr if you can call it that

.github/workflows/compile_changelogs.yml
It still doesn't run the way it should so I'll change it to see if it actually works
i didn't rewrite the whole CL cog for nothing
No
:cl:
fix: fixes the Compile Changelogs workflow once and for all
/:cl:
=> Makes workflows actually run after compile

code/controllers/subsystem/statpanel.dm, code/controllers/subsystem/ticker.dm
Add some thigns to the state pannel, QOF updates and such
A minor update to the stat panel, mostly quality of life
Gives some more detail information in game as well as a back up Round timer in case the main round timer desycs and fails to show correct amount of time.
Yes from Skyrat
:cl: radar651
add: Added Connect Players section to the stat panel
add: Added OOC status to the stat panel
add: Actual round time, a back up timer to the main round timer in-case it de-synchronizes and gives a more accurate time, to the stat panel
add: Sever time and date to the stat panel
code: added real_round_start_time to the ticker subsystem
/:cl:
=> Stat panel update

_maps/map_files/TauStation/TauStation.dmm
Some updates to Tau Station for error fixing and a new space ruin
Makes tau spicier
:cl:
add: Added new space ruin to station
tweak: Adjusted access on chemistry maintenance door
tweak: moved things around for brig physician shower
/:cl:
=> Taustation tweaks

code/modules/projectiles/guns/ballistic/automatic.dm, code/modules/projectiles/guns/ballistic/shotgun.dm, modular_splurt/code/modules/projectiles/projectile/bullets/shotgun.dm, tgstation.dme
Some presalt fixes
It Unnerfs the shotguns from being slow to reload and some of the changes to shotgun ammo that was done by Citadel a while ago.
Balancing mostly
Nope
:cl: radar651
balance: rebalanced shotguns to not be slow to reload. The check for the 8/10s of a second delay has been removed
balance: Buckshot pellets have been boasted to 12.5 per pellet
balance: slugs made more useful, now have some AP qualities
balance: Beanbags and Rubber pellet shots do more stamina damage
balance: Changed the Tommy gun from Huge to Bulky so it can actually be stowed.
/:cl:
=> UnNerf shotguns (And the Tommy gun)

_maps/map_files/TauStation/TauStation.dmm
Updates some stuff on tau, makes the ayylmao ruin a bit scarier
:cl:
add: Droppers and cables in xenobio
add: Space sharks to the ayylmao space ruin
add:Richard
tweak: Gary is now registered as a unique pet
/:cl:
=> Taustation updates (ready for merge)

_maps/map_files/TauStation/TauStation.dmm
Tau updates.png
:cl:
add: tank holders to medbay
add: various flavor items
add: Posialert console to robo
fix: Missing atmospherics machinery
/:cl:
=> Tau Updates <ready for merge>

_maps/map_files/Mining/Lavaland.dmm, code/game/objects/structures/ghost_role_spawners.dm, modular_splurt/_maps/RandomRuins/LavaRuins/lavaland_surface_abandoned_shelter.dmm, modular_splurt/code/modules/ruins/objects_and_mobs/ash_walker_den.dm
Updates a couple things about ashies and fixes some runtimes. I'm not sure how the changelog works so please tell me if I must editthat section
:cl:
fix: Fixed a couple bugs with ashwalkers!
/:cl:
=> Small ashie update

_maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
Updates Syndie listening post to give Syndie comms agent shit to do (other than, y'know, comms agent stuff)
makes Syndie base not shit
no lol
:cl:
add: John Syndicate
qol: Kinkmate, Clothes Vendor, Ore Silo and ORM, Protolathe board, some other shit I probably forgot
tweak: Replaced Circuitry with Botany
/:cl:
=> Syndie base shit

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/PubbyStation/PubbyStation.dmm
stasis beds are fucking terrible
stasis beds are fucking terrible
:cl:
tweak: reverts the shitshow with the terrible fucking stasis beds
/:cl:
=> stasis beds are fucking terrible

modular_splurt/code/datums/interactions/cuddling.dm, tgstation.dme
Completes bounty https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/issues/266
I don't give a shit i need money broke
i made this myself i am so good
:cl:
add: added cuddling interactions
/:cl:
=> [Bounty] Adds cuddling

modular_sand/code/modules/mob/living/silicon/robot/robot_modules.dm, modular_splurt/code/modules/mob/living/silicon/robot/robot_modules.dm
An upgrade for the Ghost Cafe Cyborg, extra items to make it more useful
Ghost Cafe Borgs were woefully under-equipped, this fixes that
Cafe Borgs were under-equipped. This gives them some extra things to help keep the Cafe in working order.
No.
:cl:
change: Replaced Mini-extinguisher with a full-sized one
add: Light replacer
add: Advanced health analyzer
add: Cyborg Hypospray  
/:cl:
=> Ghost Cafe Borg upgrade

modular_sand/code/modules/jobs/job_types/_job_alt_titles.dm, modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm, tgstation.dme
Initially, I just wanted to add bard alt job title for an assistants, but @BongaTheProto asked to modularize the code. Knowing that previous additions to alt titles were not modularized my non-sober mind decided to refactor code to be modular.
Contributors to Alt Job Titles code:
@DrNukesky
[E](flameghoster@gmail.com)
Modularized code = less upstream merge conflicts.
No.
:cl: DrNukesky, E, Anonymous (modularization by Anonymous)
code: Most of alt title jobs are now modularized. <b>Be sure to check your job titles in case if new code resets them</b>.
add: Bard (as an assistant's alternative job title).
/:cl:
=> Modularizes most of the alt title jobs (also adds Bard alt title)

code/modules/research/techweb/nodes/medical_nodes.dm, modular_splurt/code/modules/research/designs/medical_designs.dm, modular_splurt/code/modules/research/techweb/nodes/medical_nodes.dm, tgstation.dme
Fixes availability of the genital fluid and slave implants.
These were both in the code but not able to be researched or printed. Fixing things is good for the game.
No, this stuff was already here from other pull requests.
:cl:
fix: fixed in character availability of the gfluid and slave implants.
/:cl:
=> [BUG FIX] Implant avalibility

code/modules/projectiles/boxes_magazines/internal/shotgun.dm
:cl:
fix: The Yeehaw update was a mistake of shitcode. One error at a time, it shall be corrected and phased out.
/:cl:
=> Fixes bug with super-expensive shotgun

modular_splurt/code/_onclick/observer.dm, tgstation.dme
With the GHOST_INTERACTION config flag, ghosts can now slap the ass of players who have the ass slap pref enabled! Neat!
Why not? It's able to be disabled pretty easily via a config flag.
Not at all
:cl:
add: The ability to slap the ass of physical beings as a ghost. Spooky ☠☠
/:cl:
=> Ghost ass slapping has arrived

code/modules/projectiles/projectile/energy/stun.dm, modular_splurt/code/modules/projectiles/ammunition/ballistic/pistol.dm, modular_splurt/code/modules/projectiles/projectile/bullets/rifle.dm
A set of changes to taser electrodes and some projectiles, tweaked to be more viable and less lethal in some regards.
Making the hybrid taser electrodes and non-1911 electrodes more viable.
Ported from my own git here: https://github.com/JessieProudmore/S.P.L.U.R.T-Station-13-BIG-GUNS-
:cl:Jasmine
balance: rebalanced something
fix: fixed a few things
/:cl:
=> Weapons tweaks

modular_sand/code/game/objects/items/fleshlight.dm
This PR replaces placeholder text provided in PR #317 for... Unorthodox interaction text.
Providing as-is without further checks because it is not my thing.
:cl: Anonymous
spellcheck: Replaces placeholder text for specific fleshlight interaction with proper one.
/:cl:
=> Replaces placeholder interaction text with proper one

_maps/_basemap.dm, _maps/map_files/CogStation/CogStation.dmm, config/maps.txt
Hopefully fixes Cog Map
Cog Map's been broken a long time. This _should_ fix it.
No
:cl:
fix: fixed Cog Map
/:cl:
=> Cog Station Rework

_maps/map_files/CogStation/CogStation.dmm
Extends the Cargo Bay to give more room, lead-lines the turbine to help prevent irradiating Cargo Bay
Just more fixes for Cog Station
No
:cl:
tweak: Expanded Cargo (Cog)
tweak: Lead-Lined Turbine (Cog)
/:cl:
=> More Cog Fixes

modular_splurt/code/modules/clothing/suits/miscellaneous.dm
Due to their mutantrace flags, some of them wouldn't show a sprite when in ditigrade legs, this should fix both of the instances of it happening I found.
Please make sure to tell whenever this kind of stuff happens so I can give it a look, there are probably more like these out there
why wouldn't it be?
No
:cl:
fix: Fixes digi sprites for flannel jackets, soft hoodies and polychromic windbreakers (do tell if you find any more broken sprites please!)
/:cl:
=> Fixes some digi instances of /obj/item/clothing/suit/toggle

code/modules/mob/living/silicon/pai/pai.dm, modular_splurt/code/modules/mob/living/silicon/pai/pai.dm, tgstation.dme
Allows pAIs to select gender and have correct genitals display on Interact With. (All the hard work was done by others, literally just pulled from the borgs)
pAI not in card form could already interact with others, and had an anus as default. This just allows them more freedom to play how they'd want to.
Pulled over from modular_splurt/code/modules/mob/living/silicon/robot/robot.dm
:cl:
add: Added pAI gender selection
/:cl:
=> pAI Gender

modular_splurt/code/modules/mob/living/simple_animal/simple_animal.dm, tgstation.dme
Title.
I wanted to do xenos instead, but I forgot they require _proper_ genitals and not some easy solution.
N/A
Nope.
:cl: Anonymous
add: Players, who somehow ended up controlling a simple mob, now can change their genital set just like robots and pAIs.
del: My sanity.
/:cl:
=> Allows players who control simple mobs to change their set of genitals

code/__DEFINES/rust_g.dm, dependencies.sh
Updates rust-g to the aforementioned version and activates all of its features.
At this point it may help with the lag, who knows
No
:cl:
code: Updates rust-g to version 0.7.0
/:cl:
=> Rust-g update to 0.7.0 [DANGEROUS...?]

modular_splurt/code/game/object/items/implants/implant_aphropumps.dm, modular_splurt/code/modules/vending/kinkmate.dm
Just changing some stuff from that bounty (PR #397 )
It makes the use of both implants more intuitive
**Nop**
:cl:
tweak: Icon change of the new KinkMate's items
tweak: Added a new examine text to the new KinkMate's items
/:cl:
=> Minimal tweaks here and there for the (hexa)crocin pumps

modular_sand/code/modules/jobs/job_types/_job_alt_titles.dm, modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm, modular_splurt/code/modules/jobs/job_types/brigdoc.dm, modular_splurt/code/modules/jobs/job_types/peacekeeper.dm
I added a nuts ton of new alternate job titles. Finished two suggestions in the process of making it, linked below
https://discord.com/channels/908082639704064051/929824201001545779/1001367742957502525
https://discord.com/channels/908082639704064051/929824181787430993/995715069734289481
No downside to having more job titles, plus there's a few in there that I think might be fun.
No
:cl: 567Turtle
add: New Captain alternate job title, "Condom"
add: New HoS alternate job title, "Head of Slutcurity"
add: New Atmos Tech alternate job title, "Atmos Plumber"
add: New Assistant alternate job title, "All-Purpose Fleshlight, Greytider, Cumdump"
add: New Cook alternate job title, "Prey Prepper"
add: New Curator alternate job titles, "Scholar, Historian, Archaeologist"
add: New Chemist alternate job …
=> New Alternate Job Titles

modular_splurt/code/modules/projectiles/boxes_magazines/external/pistol.dm
title, continuation of https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/commit/702b7771713ab0ea8538cc560b1248752b71d747
Fixes some silly path errors that have been in the code since they were pr'ed
Instance #8029384 of why someone should review radar's shitcode 
No
:cl:
fix:Makes the .45 Stun and Enforcer .45 Laser ammo boxes actually spawn the correct type of ammo from lathes
/:cl:
=> Makes some lathe designs spawn the correct type of ammo

config/config.txt, config/splurt/connections.txt, config/splurt/general.txt, modular_splurt/code/controllers/configuration/entries/splurt_connections.dm, modular_splurt/code/controllers/configuration/entries/splurt_general.dm, modular_splurt/code/modules/client/client_procs.dm, tgstation.dme
Adds a toggleable option to automatically kick players who are flagged as using a vpn by the ipintel system
WARNING: I have no idea how ipintel calculates the likelyhood of the connection made being a vpn, so be aware it may not be perfect.
I HATE GRIEFERS I HATE GRIEFERS
no
:cl:
server: Adds the option to kick players who are likely connecting through a vpn on join
code: reorganizes modular config code just a bit
/:cl:
=> VPN autokicker

code/modules/projectiles/boxes_magazines/external/magweapon.dm
Fixes something that's been bugging me. Considering SPLURT isn't very combat heavy, I would hope that if you're using a mag rifle, you're primarily using these non-lethal rounds. Turns out, the non-lethal rifle size magazine is the parent item of all the other mag rifle and pistol magazines, and it doesn't have a name set. All the other magazines have a name override, this one just never got one in the first place, and in _box_magazine.dm, any magazine with no name set gets the default name of "ammo box (null_reference_exception)". So, I just added a name to it, now you can tell what it is in your inventory.
It's a bug/oversight fix, that directly improves user experience.
Nope. I researched it and made it myself. Did check another codebase that had mag weapons, it was broken there too.
- …
=> [BUG FIX] magrifle non-lethal magazine no longer says "null_reference_exception"

code/modules/admin/admin_verbs.dm, config/splurt/connections.txt, modular_splurt/code/controllers/configuration/entries/splurt_connections.dm, modular_splurt/code/modules/admin/verbs/discordbunker.dm, modular_splurt/code/modules/admin/verbs/vpnbunker.dm, modular_splurt/code/modules/client/client_procs.dm, tgstation.dme
follow-up to https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/440
Adds a whitelist that allows players in it to not be kicked if caught by the vpn blocker
Some people would like to still use vpns while playing here. I guess they can be given the pass if they're not here to grief
No
:cl:
server: adds a bypass list for the VPN blocker
admin: adds verbs to toggle the VPN blocker and also add people to the bypass list for a round
spellcheck: Fixes some typos in the discordbunker verbs
/:cl:
=> VPN whitelist 

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm, modular_splurt/code/modules/jobs/job_types/psychologist.dm
Adds four new alt titles for psychologist:
Hypnotist, Hypnosis Expert, Hypnotherapist, and Sex Educator.
Someone suggested it and I got a boner.
Furthermore, actually utilizes the alt title file for psychologist's alt titles. Because this is SS13, a separate file was made for alt titles, except later down the line someone decided to stop using it and placed some alt title lists in the job file direction, so it is unorganized. Wonderful. Some jobs still do this, and no, I won't fix it. Unless someone wants me to.
Easily identifiably hypnosis content = I AM FORNICATING.
No.
:cl:
add: Hypnotist alt-title for Psychologist
add: Hypnosis Expert alt-title for Psychologist
add: Hypnotherapist alt-title for Psychologist
add: Sex Educator alt-title for Psychologist
fix: Psychologist alt-titles now …
=> Psychologist Hypno alt-titles

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/PubbyStation/PubbyStation.dmm, _maps/map_files/SyndicateStation/SyndicateBoxStation.dmm, _maps/map_files/TauStation/TauStation.dmm
Remaps the Psychologist offices on a few maps. Here's most of the changes, slightly inaccurate because I'm too lazy to update the screenshots: 
DELTA:  
BOX: kind of sucks still, but i cant really move it anywhere better without destroying everything
SYNDIE: this map is box but shittier
META: 
PUBBY:
I made Tau's window slightly bigger, but the location is actually probably the best on any map and there isn't a space to add a private room there, so, no room. The other maps are unchanged because I don't know which other ones are in rotation.
Better map.
No.
:cl:
del: Removed customs from delta. Very sad.
tweak: Made the psychologist window on Tau slightly bigger.
add: Redoes the psychologist's room on Delta completely. It is now where customs used to be, moved very slightly.
expansion: …
=> Psychologist office remap

code/modules/food_and_drinks/recipes/food_mixtures.dm
Changes the recipe for cake batter to use 10u egg whites 5u egg yolks so its back to the previous equivalent of just using 1 egg
Saves the pain of having to use 3 eggs for something that previously used only 1 and also having 30u leftover egg white
Nope
:cl:
code: Changes the cake batter recipe
/:cl:
=> Changes the cake batter recipe

_maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
I like the beachdome. But you know what I don't like? Sitting around with nothing to do. Now, there is more to do in the beachdome. 
Better map.
No.
:cl:
expansion: beach dome slight remap. includes better stuff and a pool and a kinkmate and like one more bum slots. play it play it oh godddd oh god
/:cl:
=> Slight beachdome remap

code/game/atoms_movable.dm, code/game/objects/effects/landmarks.dm, code/game/objects/items/tanks/jetpack.dm, modular_splurt/code/modules/mob/living/silicon/robot/dogborg_equipment.dm
Harddels fixed: Jetpacks and their gas mixture, status_display_text, and antag spawner landmarks
I have not tested this beyond booting up a round and making sure this fixes the harddels, but I do not expect these to cause issues.
Jetpack fix is from https://github.com/tgstation/tgstation/pull/57736, status_display_text changes are also from tg PRs(can dig them up if needed)
:cl:Zirok
fix: Various code issues. If there are issues related to antag spawning, jetpacks or others please report them!
/:cl:
=> Fix various hard dels

_maps/RandomRuins/SpaceRuins/spacehotel.dmm
https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/460 didn't make sure the controller got properly linked and so it's currently causing it to spew runtimes like a pool hose
Lag is already bad enough
No
:cl:
fix: fixes space hotel pool runtimes
/:cl:
=> fix space hotel pool (again)

modular_splurt/code/modules/client/loadout/hands.dm, tgstation.dme
pAI device can be now picked from loadout for 3 points, will be placed in a free hand slot.
¯\\\_(ツ)\_\/¯
Nope, though idea isn't original.
:cl: Anonymous
add: You can now get pAI device from loadout ("Hands" tab).
/:cl:
=> Adds pAI device to the loadout

modular_splurt/code/modules/client/loadout/hands.dm
Cosmetic change for loadout's pAI.
:cl: Anonymous
fix: Added description to the pAI selection in loadout.
/:cl:
=> [HOTFIX] Adds description to the loadout's pAI

code/modules/projectiles/projectile/special/rocket.dm, code/modules/research/designs/mecha_designs.dm
Fix for a mislabeled item, as well as updating it to what it does on TG, which is also break windows.
First of all, it's a fix for a misrepresented item. Fixes are always good. The security lathe should not be telling people they can print the centcom/nukies version of mech missiles, and then actually give them the nerfed station version. This PR fixes the name to match the item. And second, it ports the ability to break windows, which one would expect from a breaching rocket.
I guess so? TG fixed the window issue a while ago. And I myself put in the PR for the name fix there.
:cl:
tweak: wall breaching rockets can also break windows and grilles
fix: fixed their name in the lathe
/:cl:
=> Brm6 missile fix

code/modules/vending/security.dm
Suggestion #2979 on the discord.
Changed the availability of all three Blue Shift themed uniform parts from 1 per vendor, to 5.
Probably should have made this modular, but that seems like a waste for something so small.
And yes, I did local test it. Because I can.
All I did is tweak the number. Ideally, these would be the same cost as the other security uniforms and in the SecDrobe, but I left it as it is.
It lets more than one person shout Barney Calhoun's lines. These items are purely cosmetic changes to existing sec gear, this change is flavor/RP only.
Nope.
:cl:
qol: There are now five, rather than one of each blueshift item in SecTec vending machines.
/:cl:
=> changed blue shift uniform count from 1 to 5

modular_splurt/code/datums/components/pregnancy.dm, modular_splurt/code/datums/status_effects/pregnancy.dm
pregnancy causes lactation, ovi eggs poll like posi-brains, they won't hatch until a ghost actually accepts
yes
no
:cl:
add: pregnancy causes lactation
tweak: ovi eggs now behave like posi-brains
/:cl:
=> Pregnancy updates

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
There were three different suggestions to add alternative job titles inspired by Cyberpunk to the game. So, I did. Super simple.
Suggestion 3059.
It's just more flavor.
Nope.
:cl:
add: Some more job titles.
/:cl:
=> Suggestion #3059 Cyberpunk job names

modular_splurt/code/modules/mob/splurt_emotes.dm
Since server-chat doesn't like "omg" due being an Internet slang.
This will change `*omg` emote into `*mygod`. DEWISotT.
So people should be able to induce presence of JS. De-facto, `*omg` sees "omg" part as bad IC word (understandably).
:cl: Anonymous
fix: Changes \*omg mememote into \*mygod. "omg" is usually seen as bad IC word and server disallows using it as an emote.
/:cl:
=> Changes *omg into *mygod

code/_globalvars/lists/poll_ignore.dm, modular_splurt/code/datums/components/pregnancy.dm
Looking at you, person who made six eggs to ignore the 30 second cool down, then played them like a drum set for ten minutes straight.
This PR intends to add an ignore list to egg polls, similarly to how other ghost role requests work. You click the ignore button,  it won't ask again for that round.
This ignore list needs a global list, and thus, is not fully modular.
Allows ghosts to ignore subsequent popup requests specifically for the egg role.
No.
:cl:
qol: setup ignore list for a common and spam prone ghost poll.
/:cl:
=> Add the ability to ignore egg polls to ghosts

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
new tider alternate name: stress relief
fun name
N/A
:cl:
add: Stress Relief
/:cl:
=> new assistant alternate name: "Stress Relief

modular_splurt/code/modules/client/loadout/head.dm
Adds the bowler hat, the medical beret, and the three flowers to the loadout.
The bowler hat can already be bought from the clothesmate and is in the same price category as other hats that are already in the loadout. It also serves no purpose and is purely fluff.
The medical beret felt missing from the loadout. It also serves no purpose, other than maybe identifying the wearer as medical personel, so it's been restricted to people who would have access to the medirobe that already vends these for free.
The three flowers are a bit dubious, as they can be turned into seed or eaten as they do have certain very basic chemicals in them. However, as of [Suggestion #2977](https://ptb.discord.com/channels/908082639704064051/929824181787430993/1019373231028850719), people are overwhelmingly in …
=> Adds the bowler hat, the medical beret, and the three basic flowers to the loadout

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/PubbyStation/PubbyStation.dmm, _maps/map_files/TauStation/TauStation.dmm
Adds the waypoints for every map.
=> Waypoints!

modular_splurt/code/modules/client/loadout/backpack.dm
This allows you to grab a towel from the loadout selection (backpack category).
Suggestion 3215.
Nope.
:cl: Anonymous
add: You can now grab a towel from loadout menu.
/:cl:
=> Adds towel to the loadout

modular_splurt/code/datums/traits/neutral.dm
Fixes a small capitalization mistake and adds a more noticeable biting message for victims.
No more sneaky bites.
No
:cl:
tweak: fix capitalization issue and change some of the working for vampire quirk
add: more noticeable biting message for vamp victims
/:cl:
=> Minor edits to vampire quirk

code/modules/mob/living/carbon/carbon_defense.dm, modular_sand/code/datums/traits/negative.dm, modular_splurt/code/datums/traits/good.dm, modular_splurt/code/datums/traits/negative.dm, modular_splurt/code/datums/traits/neutral.dm
goes through some of the subpar grammar scattered throughout the traits files and makes them look less more consistent and visually appealing
it's a sex server so let's make the text actually look like it was written by someone who passed an english semester
no
:cl:
spellcheck: traits
/:cl:
=> fixes traits grammar generally

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm, modular_splurt/code/modules/jobs/job_types/bridgeofficer.dm
Does Exactly What It Says in the Title.
Peacekeepers have "Rookie" title, and (I think) it is more fitting for them. Bridge Intern title is for memes alone.
Also, "Off-Duty" is now at upstream.
N/A
:cl: Anonymous
add: Added "Bridge Interns" title to BOs.
add: "Waiter" as an alt title for Assistant.
del: "Rookie" alt title is removed from sec offs (since peacekeepers have it more fittingly).
del: Removes "Off-Duty" title in modular file since upstream have it (as "Off-Duty Civilian").
/:cl:
=> Alt Title changes number 9 with extra dip

modular_splurt/code/modules/client/loadout/suit.dm, modular_splurt/code/modules/client/loadout/uniform.dm
Does Exactly What It Says in the Title.
:cl: Anonymous
add: (Blue) Apron, overalls and Amish suit are now available via loadout.
/:cl:
=> Adds apron, overalls and Amish suit to loadout

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
Adds "Commissar" alt title for HoS
:cl: Anonymous
add: "Commissar" alt title for the Head of Security.
/:cl:
=> Yet Another Alt Title

modular_splurt/code/game/objects/items/lewd_items/leash.dm
oneline change which lets you use leashes on other collars a pet would hypothetically wear
yeah
no
:cl:
tweak: hypothetically allows you to leash cowbells and maid collars for erotic purposes
/:cl:
=> hypothetically allows you to leash cowbells and maid collars for erotic purposes

_maps/map_files/CogStation/CogStation.dmm
Makes a number of adjustments, mainly around the medical area.
Commit 1 replaces the never used medical records computer which we have plenty of all around the place with a desperately needed limb grower.
Commit 2 places two additional tables at surgery beds and moves the surgery kits onto said tables.
Commit 3 removes the shared chem heater in the middle of chemistry and replaces it with the grinder, instead each chemist gets it's own chem heater next to their dispenser + chemmaster setup.
Commit 4 Places a windoor with medical access into medbay storage onto the table that medical shares with robotics and currently only has a single windoor that has robotics access.
Commit 5 Adjusts the rotation of one of the conveyor belts surronding the station.
Commit 1 is a must, every other station …
=> Cogstation (mainly) medical adjustments

code/modules/holiday/halloween/jacqueen.dm
About The Pull Request
This PR adds new trick for a Jacqueline, that fills you with some hexacrocin or changes your gender.
Why It's Good For The Game
I mean, why not
Changelog
🆑
:add: new spicy trick to Jacqueline
/🆑
=> Jacqueline update

code/datums/ruins/space.dm, modular_splurt/_maps/RandomRuins/SpaceRuins/spacehotelsplurt.dmm, modular_splurt/code/datums/ruins/space.dm, modular_splurt/code/game/area/areas/ruins/space.dm, modular_splurt/code/game/objects/items/cards_ids.dm, modular_splurt/code/game/objects/structures/ghost_role_spawners.dm, tgstation.dme
Adds a new reworked space hotel featuring more to do for the staff, a renovated bar and club and a new Manager role.
Contains materials for building Quantum Pads back and forth from the station, an engineering and service techfab and a smattering of resources. 
Current space hotel is a pretty sad and lonely ghostrole, and by and large a waste of space ruin budget when it spawns as it sees little traffic.
:cl:
A chain of space hotels has been bought out by Nanotrasen and will begin servicing nearby stations!
=> Hotel rework

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
About The Pull Request
This PR adds new job titles from Suggestion #3254 and #3214
Why It's Good For The Game
Variety of job titles is always good>?
Changelog
🆑
:add: New job titles for Cook and Detective.
/🆑
=> New job titles for Cook and Detective

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/generic/CentCom.dmm
Does  a little bug fix to box station
=> box station bug fixes.

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
Does Exactly What It Says in the Title.
:cl: Anonymous
add: Alt Title for Assistants: "Freeloader".
/:cl:
=> Adds freeloader as assistant's alt title (Suggestion #3419)

modular_splurt/_maps/RandomRuins/SpaceRuins/spacehotelsplurt.dmm
Fixes some issues with graphics on the new hotel map, as well as access.
Opens up the bar area, removes the second bar, and merges the club into the bar.
Makes a few places more secure, added an omnilathe in the engi backroom so each department can print the things they need.
=> Hotelupdates

modular_splurt/code/modules/mob/living/carbon/human/simple_animal/hostile/deathclaw/funclaw.dm
It fixes funclaws so they actually work, instead of just walking up and holding you sensually
Horny
No
:cl:
fix: fixed Funclaws, so Doge can be happy in life
/:cl:
=> Funclaw fixes

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
Does Exactly What It Says on the Tin.
Counterpart is nice.
:cl: Anonymous
add: New Assistant Alt Title: "All-purpose dildo".
/:cl:
=> Added "All-purpose d!ldo" as alt title for assistant

_maps/splurt_maps/templates/hilbertshotel.dmm
Literally adds an automatic tcomms relay to the template map of infinidorms.
Added per suggestion 3586, so you can hear drama in general & security while having a -good- time in dorms.
No.
:cl:
add: Tcomms relay (Auto) on infinidorms and a single catwalk.
/:cl:
=> Update to infnidorms

modular_splurt/code/game/objects/items/stacks/sheets/sheet_types.dm
_Suggested by Seltzer#0647 on Discord._
Adds a new method for loading cloth sheet recipes, and adds the Handmade Collar to it.
The item is named Handmade Collar, but cannot be made by hand! Figuratively unplayable!
No.
:cl:
tweak: Handmade Collar is now craftable
/:cl:
=> Allow hand-crafting the Handmade Collar

modular_splurt/code/modules/vending/clothesmate.dm
CHRIST IS RISEN!!!!!!!!!
Upstream forgor about this for like 3 years so I guess I gotta do it
No
:cl:
tweak: Christmas clothing will appear in the clothesmate when it's Christmas
/:cl:
=> Add Christmas event clothing to Clothesmate

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/TauStation/TauStation.dmm
**_In Taustation:_**
So the main scrubber loop was missing a pipe at the security main entrance that stopped the loop from being complete and cut off the security, command and dorms area from the main scrubber loop, Added more backup pipes
**_In Boxstation:_** 
Fixed the garden's vent going to nowhere
Fixed the Lawyer's office APCs
**_In Taustation:_**
So I realized while playing engineering that the main scrubber loop to sec, command, and dorms area were all going through one pipe which was connected to the main loop through a pipe going through security's main entrance
But that pipe was missing so I fixed that
And also added two other connections to the loop to ensure the loop is not a straight line but rather an actual loop
**_In Boxstation:_**
The garden's vent was noticed to not be …
=> Fixed a piping in Taustation, and Boxstation's Garden and lawyer office

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
Adds the title of "Rack Researcher" to the scientist role.
_Originally from Suggestion #3646 by Костян#6427
Adjusted to sound more "professional"_
Rack-based _"research"_ is an efficient method of earning science points.
No.
:cl:
add: Added new Scientist title: Rack Researcher
/:cl:
=> New scientist title: Rack Researcher

modular_splurt/code/modules/client/loadout/suit.dm, modular_splurt/code/modules/clothing/kinkyclothes.dm, modular_splurt/code/modules/clothing/suits/jobs.dm, modular_splurt/code/modules/vending/clothesmate.dm
Fixes tunnel fox jacket (singular) and HoP parade jacket
Tunnel Foxes rule! We're the Tunnel Foxes! That's us... And we rule!
No
:cl:
code: Tunnel Foxes rule!
code: We're the Tunnel Foxes!
code: That's us...
code: And we rule!
del: Removed open Tunnel Fox jacket
tweak: Tunnel Fox jacket is now toggleable
fix: Tunnel Fox jacket and HoP parade jacket now show up on digitigrade sprites
/:cl:
=> Tunnel Foxes Rule!

code/game/objects/structures/flora.dm, modular_splurt/code/game/objects/structures/flora.dm
This is an emergency nerf to the Christmas tree gift list, after it gave out some items that were a little too disruptive. This is a host request.
Debug uplinks, singulos, and SM swords are too awesome for Christmas.
Newp.
:cl:
tweak: changed the anything gift list to the santa gift list
/:cl:
=> [MODULAR] Emergency Christmas nerf

modular_sand/code/modules/clothing/refactor.dm
Fixing techpriest robe for anthro
Because anthro can wear this robe
No
:cl:FromRussiaWithLove
fix: fixed techpriest robes for anthro
/:cl:
=> Fix techpriest robe for anthro

modular_splurt/code/datums/ai_laws.dm
https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/659/commits/b940a1e9a691aacb56e60556582a25e54100ea8f failed to update the clarifying/cosmetic appends to the laws when changing the priority of 'sate as many crewmembers' law
grammar checker's note: the priority of the 'sate as many crewmembers' law shouldn't have mattered in the first place due to server rules saying that scenes/erp/sexual whatever aren't bound by silicon laws. it's why dogborgs can roleplay biting people people on asimov despite the fact it's quite clearly `harmful`
silicon law priority sucks
this question's still stupid
:cl:
spellcheck: horny ai law priority
/:cl:
=> `fixes` horny ai laws

code/controllers/subsystem/statpanel.dm
I made displaying game mode in status panel
Because players will know about current game mode in round
Nope
:cl:FromRussiaWithLove
add: Displaying Game Mode in status panel
/:cl:
=> Game mode in status panel

modular_splurt/code/datums/interactions/lewd/_lewd.dm
Fixes simple spelling errors in the player interactions list. Originally reported and requested by user _Toast_.
Spelling and grammar are an important part of modern language.
No.
:cl:
fix: Fixed spelling mistakes in the interaction system
/:cl:
=> Interaction spelling fixes

modular_sand/code/modules/mob/living/carbon/human/examine.dm
yeah that's it
it's consistent
:cl:
spellcheck: You
/:cl:
=> changes an `I` to a `You` to remain consistent in the way examining people refers to `The Player`

modular_splurt/code/modules/clothing/glasses/_glasses.dm, modular_splurt/code/modules/clothing/glasses/hud.dm, modular_splurt/code/modules/clothing/gloves.dm, modular_splurt/code/modules/clothing/head/helmet.dm, modular_splurt/code/modules/clothing/head/jobs.dm, modular_splurt/code/modules/clothing/head/misc.dm, modular_splurt/code/modules/clothing/kinkyclothes.dm, modular_splurt/code/modules/clothing/lewd_clothing/collar/kink_collars.dm, modular_splurt/code/modules/clothing/lewd_clothing/eyes/hypnogoggles.dm, modular_splurt/code/modules/clothing/lewd_clothing/foot/lewd_shoes.dm, modular_splurt/code/modules/clothing/lewd_clothing/head/deprivation_helmet.dm, modular_splurt/code/modules/clothing/lewd_clothing/head/hats.dm, modular_splurt/code/modules/clothing/masks/gasmask.dm, modular_splurt/code/modules/clothing/masks/miscellaneous.dm, modular_splurt/code/modules/clothing/shoes/miscellaneous.dm, modular_splurt/code/modules/clothing/spacesuits/hardsuit.dm, modular_splurt/code/modules/clothing/suits/armor.dm, modular_splurt/code/modules/clothing/suits/heavy.dm, modular_splurt/code/modules/clothing/suits/jobs.dm, modular_splurt/code/modules/clothing/suits/miscellaneous.dm, modular_splurt/code/modules/clothing/suits/vest.dm, modular_splurt/code/modules/clothing/under/jobs/civilian/civilian.dm, modular_splurt/code/modules/clothing/under/miscellaneous.dm
Fixes various typographical errors in the modular clothing files.
Spelling and grammar are an important part of modern language.
No.
:cl:
fix: Fixed spelling mistakes in server's clothing entries
/:cl:
=> Clothing spelling fixes

modular_splurt/code/modules/mob/splurt_emotes.dm
some don't have periods
some don't sound right
some have a goofy `key_third_person`
some could use annunciation`!`
yeah
:cl:
spellcheck: the meme emotes
/:cl:
=> meme emote punctuation pass

modular_splurt/code/datums/traits/trait_actions.dm
This PR serves to enhance the functionality and integration of Hypnotic Gaze without changing it's core behavior.
The following changes have been made:
- Adds comments
- Adds feedback for all fail conditions
- Adds pronoun support
- Adds checks for the following
- - Mindshield
- - Sleep immunity
- - Carbon human target
- - Non-con preference
- - - This allows skipping the consent prompt
- - Combat mode
- - Eye protection
- - Covered eyes (Unused)
- - Blindness
- - Valid mind
- - Anti-magic (excluding holy)
- - Cyborg target
- - Alien target (Unused)
- Adds a sound effect on successful triggering
- Removes unnecessary checks
- Reduces action time from 12s to 5s
- Reduces the required number of user inputs
- Updates variable names to match standards
- Updates hypno pref check to use …
=> Hypnotic Gaze quirk improvements

modular_splurt/code/modules/research/techweb/nodes/robotic_nodes.dm
tin
bugfix
:cl:
fix: ai research
/:cl:
=> fixes the horny ai modules not being researchable

code/__HELPERS/unsorted.dm
So, it seems that passing user was missed in one of the proc calls for the tgui menu in https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/464, which made it impossible to create some types of variables with vv. This should fix it
proper ~~adminbussing~~ variable editing
No
:cl:
fix: fixes datum reference, typepath, and other tgui-dependant variable editing options
/:cl:
=> Fixes datum vv

modular_sand/code/datums/elements/holder_micro.dm
makes you able to interact with mobs you're holding again
Fixes an issue brought up when the interaction menu update happened
brings back some of our custom content
:cl:
fix: Makes you able to interact with mobs you pick up again
/:cl:
=> Fix micro interactions

modular_splurt/code/modules/vending/barkbox.dm
Adds leashes to the barkbox because... I am surprised there are collar selection and stuff, but not the leashes.
Stop letting dogs out unleashed goddammit.
Nope.
:cl: Anonymous
add: Leashes are now available in BarkBox as well.
/:cl:
=> Adds leashes to the barkbox

code/__SPLURTCODE/DEFINES/traits.dm, modular_splurt/code/datums/traits/neutral.dm
Adds a new quirk which allows people to morph their bodies like slimes, the quirk is neutral
This adds the existing ability through the quirk
More customization for people's characters
Someone asked if the slime shift ability is available to other species and I didn't see any way for that, so I added it
No
:cl:
add: Added new body morpher quirk, which allows people to morph like slimepeople
/:cl:
=> Body Morpher Quirk

code/modules/mob/living/silicon/robot/robot_modules.dm
titl
another small fix
literally just changed one letter
Mining RoboMaid model works properly now
literally, just ONE non-capitalized letter was changed in this PR
that is all it took to fix this damn model
all the trouble I had to go through, of finding the line for the borg and figuring out what the fuck was wrong with it
lead me to change ONE letter
and now I'm making a PR changing one damn letter
at least it's a fix
it manages to fix something
and so I am asking for its push
because
it's a fix
I have honestly put more work towards making this description
for a joke
because this whole PR with a long-ass description
that fixes a borg model
by changing ONE letter
is pretty funny, eh?
anyways
this is all I have to say
it's a fix
ye
f i x
like usual
naaaaaah
:cl:
fix: mining RoboMaid model …
=> Mining RoboMaid fix

modular_splurt/code/modules/projectiles/boxes_magazines/ammo_boxes.dm
Actually adds the ammo boxes for 5.43mm ammo and kaiju ammo!
Reloading issues no more!
Non
:cl:
add: 5.43 ammo box
add: Kaiju ammo box
/:cl:
=> 5.43mm ammo box

modular_splurt/code/game/objects/items/armor_kits.dm
Basically, if you use an armouring kit on a suit, it now adds the suit storage for the appropriate vest.
IE: adding the security kit to a jacket will allow the jacket to hold whatever a security vest could hold in the suit storage.
Makes kitted swag more similar to the non swag counterpart.
Not a port.
:cl:
tweak: Allows uparmoured items to hold items like their vest counterparts.
/:cl:
=> Makes Aegis and Rampart reinforcement kits add appropriate suit storage slots.

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/OmegaStation/OmegaStation.dmm, _maps/map_files/PubbyStation/PubbyStation.dmm, _maps/map_files/TauStation/TauStation.dmm
Standardises Security access to the Permabrig, office and Arrival Security checkpoint to allow Peacekeepers in/not trap them in their spawnpoints.
Fixes a maint door on pubby set to let anyone into medbay.
Adds Blueshield, Bridge Officer, Brig Doc and Psychologist jobs to Omega, as well as a smoll brig medbay. Should be a functional map now.
:cl:
fix: Fixed up sec access for Peacekeepers.
add: Blueshield/Bridge Officer/Brig Doc/Psychologist on Omega. Also has a small brig medbay. Should be a functional map now.
/:cl:
=> Mapping bugfixes

modular_splurt/code/game/objects/items/lewd_items/chastity_hypno/chastity_hypnosis.dm
Makes mannitol not send chastity-related messages unless you do have any related effects on you
fix
No
:cl:
fix: Fixes mannitol sending chastity messages unnecesarily
/:cl:
=> fixes mannitol

code/__DEFINES/access.dm, modular_splurt/code/game/objects/items/weaponry/melee.dm, modular_splurt/code/modules/jobs/job_types/peacekeeper.dm
Yet another Peacekeeper Rework. This time, they've lost their tasers and now have a choice of batons! Coming soon: Peacekeeper Offices!
Reworks Peacekeepers (Again), this time removing their tasers and giving them a Choice Beacon for a selection of batons. Also prepares them for dedicated Peacekeeper offices in the future.
The Peacekeepers are intended to be an RP Role, but try too hard to be Security. This aims to rectify that slightly.
No.
:cl:
add: Peacekeeper Choice Beacon
add: Preparation for map additions
del: Tasers from Peacekeepers
tweak: Peacekeeper access
tweak: Peacekeeper supervision
/:cl:
=> Peacekeeper Rework

code/__SPLURTCODE/DEFINES/cooldowns.dm, modular_splurt/code/datums/interactions/lewd/lewd_datums.dm, modular_splurt/code/datums/traits/good.dm, modular_splurt/code/game/objects/items/implants/implant_disrobe.dm, modular_splurt/code/modules/mob/living/carbon/carbon.dm, modular_splurt/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Title
less bugs and more content, what more can you ask for right?
I suppose the verb is from our old codebase *shrug
:cl:
add: adds the clothesplosion verb which lets you burst out of your clothes
fix: adds a delay to the well trained blushing so that our subs don't go spamming blushes everywhere
/:cl:
=> Fixes the blushing bug and adds clothesplosion verb

_maps/map_files/layenia/layeniastation.dmm, modular_splurt/code/game/turfs/open.dm
Removes the secondary apc from tcomms, should fix ~~daddy~~ power issues
I wondah why
Non
:cl:
del: Secondary apc
/:cl:
=> Layenia tcomms fix

modular_splurt/code/modules/clothing/suits/miscellaneous.dm
sydnicate
whar
no :(
:cl:
fix: sydnicate -> Syndicate
/:cl:
=> 1 line fix (months taken)

code/modules/mob/living/emote.dm, modular_splurt/code/modules/mob/living/emotes.dm
Makes it so ghost can't use *speen. It does not give them a message saying they can't.
People complained about ghosts using *speen to interrupt hot ERP
Negative.
:cl:
fix: Ghost can't Speen anymore, fixed a small part of code that wasn't finished (return FALSE). If it breaks blame Kepler xD
wip: Could be improved so it tells you that you can't do it. For more info look into: code/datums/emotes.dm line 115. 
/:cl:
=> Speen_Ghost_Fix

code/modules/arousal/organs/breasts.dm, code/modules/arousal/organs/butt.dm, modular_splurt/code/modules/arousal/organs/belly.dm
apparently that pr removed the limits to those two genitals that DO need limits
no more sudden balls implosion
no
:cl:
fix: Bellies and butts won't suddenly disappear when expanding
/:cl:
=> genital bugfix

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
Exactly What It Says on the Title.
Since we have xenoarch merged.
Formally, old Skyrat code.
:cl:
add: Xenoarchaeolgist alt title for scientists.
/:cl:
=> Adds Xenoarchaeolgist alt title for science

code/modules/client/verbs/ooc.dm, modular_splurt/code/datums/genitals/genitals_interface.dm
Removes a privacy-violating feature or two.
As a future note to anyone reading this, please ensure the non-modular change is never reverted.
----
N
:cl:
del: Ability to link CKEYS & Characters as a non-admin
del: Ability to see genitals on all mobs regardless of clothes with a verb.
/:cl:
=> Privacy PR

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
Adds "Sexual Advisor" as an alt title for Psychologist.
Suggestion 5062. People may finally learn how do sex in-game.
:cl: Anonymous
add: Sexual Advisor as an alt-title for Psychologist.
/:cl:
=> How do I sex 2???

_maps/RandomZLevels/VR/snowdin_VR.dmm
fixes snowdin VR missing texture tiles
pink/black tiles ugly, remove
no
:cl:
fix: missing textures
/:cl:
=> Snowdin VR missing texture tiles

code/modules/movespeed/modifiers/mobs.dm
broken for 2 years+ btw
fixes a trait
no
:cl:
fix: config_wak_run -> config_walk_run
/:cl:
=> Most Intelligent Coding Mistake.

_maps/RandomRuins/SpaceRuins/listeningstation.dmm, _maps/RandomRuins/SpaceRuins/listeningstation.dmm.old, _maps/RandomRuins/SpaceRuins/listeningstation.dmm.phzold, code/modules/ruins/lavaland_ruin_code.dm, modular_splurt/_maps/RandomRuins/SpaceRuins/syndielistenspace.dmm, modular_splurt/_maps/RandomRuins/SpaceRuins/syndielistenspace.dmm.old
This PR includes a pretty big update for the Space Comms Agent's Base. It allows two people to spawn in and expands the outpost to be more comfortable and makes it a lot less claustrophobic.
it makes an aspect of the game that basically nobody plays a lot more fun and can bring people to try out a ghost role that has been left virtually untouched for quite some time. Comms agent gameplay has not been changed, but the living conditions have been made a lot better.
nope
:cl:
add: added old versions of the maps listeningstation.dmm and syndielistenspace.dmm as .old
add: Added a living room in the space comms base, made the bathroom bigger, added a second sleeper for another ghost to spawn in, made bedrooms bigger, expanded medbay a little bit to factor in having an operating table, tweaked a …
=> Space comms base rework

code/game/machinery/cryopod.dm
Same as #934 , but a little different
idk really
a fix
:cl:
fix: fixes cryoing characters without mind
/:cl:
=> Fixes cryopods (v2)

code/modules/arousal/organs/breasts.dm, modular_sand/code/datums/interactions/lewd_definitions.dm, modular_splurt/code/datums/interactions/lewd/_lewd.dm, modular_splurt/code/game/atoms.dm, modular_splurt/code/modules/arousal/arousal.dm, modular_splurt/code/modules/arousal/genitals.dm, modular_splurt/code/modules/arousal/organs/breasts.dm, modular_splurt/code/modules/arousal/organs/penis.dm, modular_splurt/code/modules/arousal/organs/vagina.dm, tgstation.dme
Historically, the cum overlay feature has been broken in our code. As it turns out, this is due to the unnecessarily complex code it used due to how it was ported. This pr not only fixes it so coating things actually works, but also makes it account for the character's genital fluid's color and also makes it so it works when spilling if your genitals are large enough.
it fucking works!!! wooooo!!!!
a fix and enhancement of a port, I suppose
:cl:
bugfix: cum overlays work now
bugfix: breasts will now work properly with size limits set
add: you may now coat objects or people in jizz using your pussy, breasts and penis
/:cl:
=> Fixes the cum overlay so you can actually cum over stuff

code/modules/jobs/job_types/detective.dm, modular_splurt/code/datums/genitals/genitals_interface.dm
Only change is adding the access "ACCESS_SECURITY". This access enables the use of the equipment room and the break room + general
Now detectives don't have to go to HoP and ask for these perms.
Negative.
:cl:
fix: as it has been clasified as a bug, it is a fix.
/:cl:
=> Detective_access_fix

.github/workflows/ci_suite.yml, .github/workflows/generate_documentation.yml, .github/workflows/update_tgs_dmapi.yml, code/datums/helper_datums/getrev.dm, code/game/world.dm, dependencies.sh, tools/ci/install_rust_g.sh
Tries to fix some rustg incompatibilities, and also tries to fix the documentation error
I suppose I had to port the other code changes too
from tg
:cl:
code: adds the other updates of rust-g
/:cl:
=> Rustg updates

modular_sand/code/modules/mob/living/simple_animal/hostile/megafauna/gladiator.dm
Adds a list length check to stop the spin animation going out of bounds and causing the gladiator to be invincible to all attacks.
Gladiator can die
Nope
:cl:
fix: Gladiator no longer stays invincible
/:cl:
=> Fix Gladiator Infinite Shield Bug

modular_splurt/code/game/objects/items/storage/firstaid.dm
Kinkmate vendors have a contraband item "breast reduction pills" it actually contained penis 
reduction pills
this pr corrects this
The pill container contains what it states it contains. 
No
:cl:
fix: Kinkmate contraband item "Breast reduction pills" now contains stated item, instead of penis reduction pills
/:cl:
=> Fixing Misconfiguration of kinkmate item

code/modules/mob/living/silicon/robot/robot_modules.dm
Adds the missing Fancy Raptor service module, and makes the use of the sciraptor + sci-catborg.
I forgor💀
Sprites ported from [ChompStation2](https://github.com/CHOMPStation2/CHOMPStation2.git) (requires a GitHub account to view).
:cl: Anonymous
add: Added fancy variant of service raptorborgs. I forgot to include it in the OG PR.
add: Repurposes ported sciraptor and sci-catborg sprites to be an alternative service (janitor) module.
/:cl:
=> I FORGOT ABOUT FANCY RAPTORBORGS GODDAMMIT (feat. adapting sci modules into service)

_maps/map_files/BoxStation/BoxStation.dmm
Simple fix for a small screw up on BZ pipes overlapping on box station, this corrects it and should allow unimpeded BZ to Test Chamber.
Small mapping fix, because well why not?
No
:cl:
Fix: Box Station Mapping Fix.
/:cl:
=> [NON-MODULAR] [READY] BZ PIPE FIX, BOX STATION.

modular_splurt/code/modules/projectiles/boxes_magazines/external/pistol.dm
Literally just fixes wacky brackets in magazine names.
More OCD stuff.
Still no.
:cl:
spellcheck: Fixed wrong brackets in enforcer mag names.
/:cl:
=> Magazine name fix

code/modules/language/language_holder.dm, modular_splurt/code/modules/mob/living/carbon/xenomorphs/alien.dm, tgstation.dme
Github decided that there'd be an imaginary merge conflict in genpop.dm despite the old PR not touching it.
I am convinced this is due to the 19 other testmerges but hey, I'll re-branch it anyway
yes
:cl:
del: Code that prevented specific mobs from being unable to be admin-assigned languages w/o varedits (fuck you)
add: Flavortext by default to Xenomorphs, OOC notes to xenomorphs
add: /station queen subtype, spawns without an eggsac and can process chemicals (thusly can be sedated)
/:cl:
=> SEX 3.0.1 | XENOFUCKER UPDATE | I HATE GITHUB BRANCH ISSUES

_maps/RandomRuins/SpaceRuins/oldstation.dmm, _maps/RandomRuins/SpaceRuins/spacehotel.dmm, _maps/RandomZLevels/away_mission/moonoutpost19.dmm, _maps/RandomZLevels/away_mission/research.dmm, _maps/RandomZLevels/away_mission/undergroundoutpost45.dmm, _maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/BoxedInStation/BoxedInStation.dmm, _maps/map_files/CogStation/CogStation.dmm, _maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/FestiveBall/FestiveStation.dmm, _maps/map_files/KiloStation/KiloStation.dmm, _maps/map_files/LambdaStation/lambda.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/OmegaStation/OmegaStation.dmm, _maps/map_files/PubbyStation/PubbyStation.dmm, _maps/map_files/SmolStation/SmolStation.dmm, _maps/map_files/Snaxi/Snaxi.dmm, _maps/map_files/SyndicateStation/SyndicateBoxStation.dmm, _maps/map_files/TauStation/TauStation.dmm, _maps/map_files/generic/CentCom.dmm, _maps/map_files/layenia/layeniastation.dmm, _maps/shuttles/emergency_cere.dmm, _maps/shuttles/emergency_meta.dmm, _maps/splurt_maps/map_files/Smexistation/Snaxi_Splurt.dmm, _maps/splurt_maps/map_files/Smexistation_OLD/Snaxi_Splurt.dmm, config/entries/urls.txt, modular_splurt/code/game/objects/items/manuals.dm
changes the space law books to use the version in our wiki instead
Avoids confusion
No
:cl:
tweak: The space law books use our wiki's space law now
/:cl:
=> Updates space law to our current version

modular_splurt/code/modules/mob/living/silicon/robot/robot_modules.dm
Simply adds back assaultron selection for standard borg module, that's it. Thanks to ct56324864 for this one.
Someone overwrote the selection of it by accident when adding F13 borgs, so no big harm.
:cl: Anonymous
fix: Standard assaultron should be now selectable again.
/:cl:
=> [FIX] Brings back standard assaultron which was removed by accident

modular_splurt/code/modules/client/loadout/backpack.dm
Does exactly what it says on the title.
It's nice, plus extra storage if needed. Suggestion 5596.
Nope.
:cl: Anonymous
add: Added box of hugs into loadout.
/:cl:
=> Added Box of Hugs into loadout

modular_splurt/code/modules/clothing/under/miscellaneous.dm
Howdy there, gents and gals, this is just a simple fix for the "Lewd Maid Outfit" appearntly not working for digitgrade characters, so I fixed it, enjoy to your wildest contents you goobers.
Just fixs the clothing for digitgrade legs.
No
:cl:
fix: Fixs Lewd Maid Outfit not being digitgrade wearable.
:cl:
=> [MODULAR] [READY] Lewd Maid Outfit Fix

modular_splurt/code/datums/components/pregnancy.dm
Makes it so miscarriages are not a thing
I wonder why
Non
:cl:
del: Removed miscarriages
/:cl:
=> Removes miscarriages!

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
See changelog!
More alt-titles!
Nope!
:cl:
add: (Job-Titles): "Synth Tech" for Roboticists, "Pred Prepper" for Cooks, "Package Handler" for Cargo Techs. "Service Top", "Service Bottom", "Service Pred", "Service Prey", "Belly Massager" and "Pet" for Assistants.
/:cl:
=> [JOB-TITLES] Adds a few alt job titles!

modular_sand/code/game/machinery/cryptominers.dm
See title!
See title, yes.
Nope!
:cl:
tweak: Stop Cryptocurrency miners from beeping every second.
/:cl:
=> [Sanity Boost, you're welcome] - Stops Cryptocurrency miners from beeping every second.

code/game/objects/items/robot/robot_items.dm
Allows the Minerborg's gripper to be more useful than only grab and use shelter capsule.
This module is rarely used to deploy capsules even when it got fixed to finally deploy it, so this PR basically should expand the utility of the minerborg's gripper.
No.
:cl:
expansion: Minerborgs can carry a few more things with the gripper: survival medipen, regenerative core and stabilizer serum.
/:cl:
=> Minerborg minor buff: Add a few things to carry with its gripper than just shelter capsules.

code/datums/elements/flavor_text.dm, code/modules/client/preferences.dm
Enables use of e621 for your image needs.
More stable links than discord, and like 5 people know the other service, discourages use of paywalled images as headshots.
Nope
:cl:
add: Use of E621 for headshots, because literally why not?
/:cl:
=> E621 images

code/modules/food_and_drinks/drinks/drinks.dm, code/modules/reagents/reagent_containers/glass.dm
Adds chugging, already existing for drinking glasses, but this time to any type of liquid container (which is different than food/drinks)
Very good.
Nope!
:cl:
add: Added chugging to any type of liquid container, not just drinking glasses.
tweak: Removed old citadelcode from reagent container drinking, for more clean and readable code.
fix: Fixes a few bugs related to chugging.
/:cl:
=> [NON-MODULAR + CLEANUP] Adds chugging to any type of liquid container + optimizes and fixes some drinking code

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm, modular_splurt/code/modules/jobs/job_types/blueshield.dm
Add more funny job titles, along with syndicate and Tech priest cult
Just a funny job titles that nobody cares of, but make sence when it comes to RP
Yes it is! Ported from BlueMoon build
:cl:
add: New job titles!
=> [MODULAR] Funny job titles

modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
Add syndicate related job titles for RP, allowing people to roleplay as EX syndicate members (not allowing for self antaganism)
RP based moment that nobody cares of. 
As usual - ported from bluemoon build
:cl:
add: New syndicate job titles
=> [MODULAR] Syndicate job titles

code/__SPLURTCODE/DEFINES/traits.dm, code/modules/reagents/chemistry/reagents/other_reagents.dm, modular_sand/code/datums/interactions/interaction_datums/lewd/kiss.dm, modular_sand/code/datums/interactions/interaction_datums/lewd/oral.dm, modular_splurt/code/datums/interactions/lewd/lewd_datums.dm, modular_splurt/code/datums/traits/neutral.dm
Adds the kiss slut trait to increase arousal when kissing/kissed, and fixes oral sex <3!
Very good!
Nope!
:cl:
add: Added the Kiss Slut trait, which increases arousal when kissing others or being kissed! 
fix: Fixed oral sex, in specific the "Go down on them verb". <3
/:cl:
=> [BOUNTY] Adds the kiss slut trait + fixes oral sex verbs

code/datums/brain_damage/severe.dm, code/game/area/areas.dm, code/modules/ruins/spaceruin_code/hilbertshotel.dm, modular_splurt/code/modules/ruins/spaceruin_code/hilbertshotel.dm, modular_splurt/code/modules/spells/spell_types/lewd.dm
See title!
Less bugs.
Nope!
:cl:
fix: Fixes monophobia quirk/trauma increasing stress levels even when grabbed by a macro character.
/:cl:
=> [BUGFIX] Fix monophobia stress increasing even when grabbed by a macro character

code/game/machinery/limbgrower.dm, code/modules/research/designs/limbgrower_designs.dm, modular_splurt/code/game/machinery/limbgrower.dm, modular_splurt/code/modules/reagents/reagent_containers/bottle.dm, modular_splurt/code/modules/research/designs/limbgrower_designs.dm
As name says lol (Fixed code so you can now print three more races bodyparts)
This will fix the limb grower problem of not being able to print certain stuff, plus it add cum and femcum as options in "Other" tab, as we do have a problem with succuby and people that need cum not being able to get it easily.
It fixes stuff and even better! you can spawn cum now.
nope
:cl:
add: Added Semen and Femcum to the limb grower
fix: fixed limbgrower not displaying shadekin, teshari and vox bodies as able to be printed
/:cl:
=> [NON-MODULAR] Fix limbgrower missing species limbs, added synthetic semen and female ejaculate

code/modules/mining/equipment/explorer_gear.dm
It is a fix of the broken miner's explorer suit 
Because fixes the miner's explorer suit sprite
No
:cl:
fix: fixed a few things
code: changed some code
refactor: refactored some code
/:cl:
=> Fixed the miner's explorer suit

modular_splurt/code/modules/client/loadout/donator/first_tier.dm
Adds the aforementioned item to the aforementioned category
Requested by donator
no
:cl:
add: Adds the Riding crop  in the donator tier 1 loadout
/:cl:
=> Riding crop donator tier 1 loadout

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/LambdaStation/lambda.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/PubbyStation/PubbyStation.dmm
Removes bugs from be37603 on Box station AI module room, merge conflict marker from 13cd269
Fixes mapping errors
Nope
:cl:
del: Removes merge conflict marker from aimodules rather than AI_modules
del: Removes double layer on core modules
/:cl:
=> Fixes bugs from be37603

code/game/objects/effects/contraband.dm, modular_sand/code/game/objects/items/plushes.dm
Fixes the susplush and steppy poster
Fixes the susplush and steppy poster
Less broke, more fix
Nada
:cl:
fix: Fixed the susplush and steppy poster
/:cl:
=> Plushie and Steppy

code/modules/mob/living/carbon/human/species_types/anthropomorph.dm
Adds "FACEHAIR" trait into anthropomorph.dm's species_traits list, allowing facial hair to be shown on anthromorph characters.
I do not see why it's good for anthromorphs to be restricted access to facial hair.
Probably just a mistake in the code that found its' way in at some point.
Not a port.
:cl:
fix: allow facial hair on anthromorph species 
/:cl:
=> facial hair for anthros hurray

code/datums/datacore.dm
It really isn't, at all
Possibly fixes the bug with crew manifests default titles
Because its a bug fix
We raw dogging it
:cl:
fix: Crew manifests default titles
add: Now shows both alt title and normal to help people who don't know what role a condom is
/:cl:
=> "Coding is my passion™"

_maps/shuttles/emergency_koipond.dmm, modular_splurt/code/datums/shuttles.dm
Adds a new shuttle, "_The Koi Pond_", for 2500 credits.
The shuttle is somewhat large (21x40), however has airlocks near the bottom to hopefully minimize docking issues. The shuttle contains a large 'outdoor' section with food items and some equipment, the interior 'house' has jukeboxes, food items, an office that houses the Shuttle Console, as well as a variety of decorations such as books, bathrooms, bedrooms, and more. There is also a maintenance section at the rear of the shuttle that has materials, tools, atmospheric equipment, and more!
While the shuttle is safe, it is notably weaker than some shuttles in terms of durability due to the large open areas. It also lacks a designated medical area, replaced by a section of the house with spare medical items.
It adds more variety to the …
=> Adds "The Koi Pond" Emergency Shuttle

_maps/map_files/CogStation/CogStation.dmm
:cl:
tweak:
- Engineering Secure Storage now has coils for tesla engine and radiation collectors
- West dock has been modified, white ship was supposed to be able to dock but was removed because it caused errors
- Bridge has been modified to include meeting room
- Bar has been modified to look similar to original cog bar
- Atmos has been expanded
- Library has been expanded
fix:
- Cargo loading conveyor belt now works
- Removed door in middle of hallway
- Some turfs are now using correct tiles
expansion:
added 2 vacant offices
qol: 
added more of privacy shutters
/:cl:
=> CogStation Update

_maps/splurt_maps/map_files/4Nalstation/4NaL_Station.dmm
Just some bug fixes to align the current version better with the post rebase version, can be directly merged.
:cl:
fix: fixed small mapping bugs
/:cl:
=> 4nal bug fixing
