SPLURT-Station/S.P.L.U.R.T-Station-13

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/Deltastation/DeltaStation2.dmm
- _maps/map_files/FestiveBall/FestiveStation.dmm
- _maps/map_files/KiloStation/KiloStation.dmm
- _maps/map_files/LambdaStation/lambda.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/OmegaStation/OmegaStation.dmm
- _maps/map_files/PubbyStation/PubbyStation.dmm
- _maps/map_files/Snaxi/Snaxi.dmm
- _maps/map_files/SpookyStation/SpookyStation.dmm
This adds a wardrobe to permabrig for every station other than Cogstation and Smolstation (the latter is so old it has minesweeper on it).
Prisoners typically don't have access to the rest of the station, so this will let them change out their underwear.
No
add: Added wardrobes to permabrig.
/:cl:
> Add Wardrobes to Perma

- code/modules/mob/living/silicon/robot/robot.dm
- modular_sand/code/game/objects/items/robot/robot_upgrades.dm
Borg expanders have two problems, they do not expand as they used two (double size), and the sprite is off-centre (not on the floor properly), this fixes both with a **temporary** solution until I find a better way to fix this.
temporary fixes the borg expander
no
:cl:
fix: gave the borg expander and borg reset codes a pixel_y += 16 and pixel_y -= 16, temporary fix
/:cl:
> Set pixel fixing for borg expander

- modular_splurt/code/modules/mob/living/carbon/human/simple_animal/hostile/deathclaw/funclaw.dm
Adds checks for general ERP consent and erp verb consent, just to be 100% certain the target is ok with being lewded.
🆑
add: Extra consent checks for funclaws, just to be safe.
/🆑
> Funclaws: Extra consent checks

- code/game/objects/items/devices/transfer_valve.dm
- code/modules/atmospherics/machinery/portable/canister.dm
- code/modules/reagents/chemistry/machinery/chem_dispenser.dm
- modular_splurt/code/modules/admin/playtimes.dm
- tgui/packages/tgui/interfaces/PlayerPlaytimes.js
Adds admin warning if a player with less than 8 hours playtime:
- Uses a Chemical Dispenser
- Touches a Transfer Valve
- Touches a Canister menu
(To avoid spam, these warnings will only display once every 15 minutes, per grief type, per player.)
These warnings also persist throughout the round on the playtime panel in the form of icons with tooltips. They will be hidden initially, and appear if the client triggers them:
Hidden chem machine bad.
:cl:
add: Admin grief warnings
/:cl:
> More Grief Warnings

- code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Stops non-chemist Chem Dispenser types from triggering a grief warning.
:cl:
fix: Grief alarm fix
/:cl:
> Fixes grief warning issue

- code/modules/client/preferences.dm
Should make them easier to spot
Adds `cursor:help;` styling to the tooltip question marks in the preferences menu.
Will make the tooltips more obvious. When the player mouses over them the cursor style will change.
Nope
:cl:
add: `cursor:help;` to all 3 tooltip spans.
/:cl:
(I didn't know whether to make a PR for this but I can't re-open the previous PR, so here's this)
> Change pref tooltip triggers to use "help" cursor

- modular_splurt/code/game/object/items/miscellaneous.dm
Update the Max Mutations per disk from 6 to 15
This was Suggestion number 28 on discord that was approved and I am finally getting around to doing it. It changes the Max Mutations from 6 to 15, nearly 3 times disk storage space. Why? Didn't the suggest say remove it? yes it did but it was hard coded in so I just upped the number to decrease disk swapping.
This was approved already, but it will make genetics live a bit easier.
:cl: radar651
tweak: Upped Max Mutations from 6 to 15.
/:cl:
> Suggestion #28

- code/game/objects/items/devices/radio/radio.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
- modular_sand/code/modules/mob/living/silicon/robot/robot_modules.dm
- modular_splurt/code/game/object/items/devices/radio/radio.dm
- modular_splurt/code/modules/mob/living/silicon/robot/robot_modules.dm
- tgstation.dme
This makes borgs to get access to their department radio when transforming into related module, without getting required radio keys from roboticists.
Saves some headache for the borgs and robotics alike...? Citadel is weird tbh.
> If you can't justify it in words, it might not be worth adding.
¯\\_(ツ)_/¯
Old Skyrat code.
:cl: Anonymous (feat. radar651)
tweak: Borgs will now get access to department radio upon transforming into respected module (e.g. security and peacekeeper modules - security channel).
/:cl:
> [SEMI-MODULAR] Ports old skyrat handling of borg radio

- modular_splurt/code/modules/projectiles/ammunition/ballistic/smg.dm
- modular_splurt/code/modules/projectiles/boxes_magazines/external/pistol.dm
- modular_splurt/code/modules/projectiles/projectile/bullets/smg.dm
Updates the .45 taser and .45 lethal
Fixes the 45 lethal mags and updates the .45 taser to be completely non-lehtal.
It fixes some bugs and fixes balance
:cl: radar651
balance: Makes .45 taser not hurt anyone at all. Its completely non-lethal.
fix: .45 Lethal now properly spawns on .45 lethal mags
/:cl:
> .45 Update

- _maps/map_files/generic/CentCom.dmm
- _maps/shuttles/slaveship_basic.dmm
- code/modules/admin/verbs/randomverbs.dm
- modular_splurt/code/game/areas/shuttles.dm
- modular_splurt/code/game/data_huds.dm
- modular_splurt/code/game/machinery/research_table.dm
- modular_splurt/code/game/object/structures/crates_lockers/closets/slaver.dm
- modular_splurt/code/modules/antagonists/slaver/equipment/orderable_gear.dm
- modular_splurt/code/modules/antagonists/slaver/equipment/slaver_items.dm
- modular_splurt/code/modules/projectiles/guns/ballistic/automatic.dm
- modular_splurt/code/modules/projectiles/guns/energy/special.dm
- tgstation.dme
- Antag target HUD test was successful. Admins can now see it when combo HUD is enabled.
- Adds new 'Collection Tool' item to the starting loadouts that removes the need to drag kidnapped crew through space to the shuttle. They can now be safely teleported to the shuttle as long as the shuttle is on the same z-level.
- Adds more buyable gear (ion weapons, lethal weapons, etc.).
- Removes most of the use of crates when buying new gear, they just flooded the hideout with useless boxes. Duffel bags are now the usual container.
- Buyable mech now comes pre-built, with many more options for customisation now.
- Removes the need to configure the slaver sex table before use.
- And other changes.
:cl:
add: antag consent HUD added to admin HUD
add: new 'collection tool' to teleport crew to the …
> Slave antag patch 2

- modular_splurt/code/modules/client/loadout/backpack.dm
It removes permits from the loadout menu
Because not everyone should have a permit and the point of permits is to show that someone is trustworthy with weapons
No
:cl:
del: Removed weapon permits from loadouts
/:cl:
> Permits fix

- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/mob.dm
Adds an option in game preferences to disable the special mouse cursor when in combat mode. Default option is to use the combat cursor.
It's hard to see in certain situations and makes people not want to use combat mode for that very reason.
:cl:
add: Adds a game preference option to disable the special combat mode cursor.
/:cl:
> Combat cursor: Adds preference to disable it.

- modular_splurt/code/datums/traits/neutral.dm
- modular_splurt/code/game/object/items/mesmetron.dm
Added additional checks for Hypno prefs for Hypnotic gaze and mesmetron
Quick update to Hypnotic Gaze and mesmetron, adding checks for Hypno prefs for both.
Final check before the Hypno procs to cut shitters off at the pass, while not punishing people for using it.
Nah
:cl:
add: Added final preference check before Hypnotic Gaze triggers on the target.
fix: Fixed Mesmetron not checking for Hypno preferences on use
/:cl:
> Hypno patch

- _maps/map_files/BoxStation/BoxStation.dmm
Moves blood bank and limb grower to Medical storage. One table removed, the items on that table moved to a nearby one so as not to crowd the room.
Main reason.
Chemists can't reach the limb grower in surgery storage, this way its more likely to be filled.
Side benefit.
More likely to be upgraded by science as they pass through.
https://user-images.githubusercontent.com/5742277/152924602-b1bd8e1c-a09e-47b5-afb9-f8c33ff5ae56.PNG
:cl:
tweak: changed some map things on box
/:cl:
> Minor boxstation medical machinery adjustments

- code/modules/events/abductor.dm
- code/modules/events/blob.dm
- code/modules/events/space_dragon.dm
- code/modules/events/space_ninja.dm
It Decreased some mid-round antag spawns so we're not facing abductors, ninjas, and dragons every round.
There's too many space dragons, ninjas, and abductors being created.
Nope
:cl: Curiosity
balance: Reduced Mid-round antags that are commonly spawning
/:cl:
> Decreases Midround Antags

- modular_sand/code/modules/jobs/job_types/_job_alt_titles.dm
This removes "mechanic" from engineering and "entertainer" from clowns. Also re-adds "blacksmith" alt title for Assistant.
Less confusion.
N/A
:cl: Anonymous
add: Added "blacksmith" as an alt title for Assistant.
del: Removes "mechanic" from Station Engineer alt titles.
del: Removes "entertainer" from Clown alt titles.
/:cl:
> Changes to alt job titles (Suggestion 70 (newer one))

- _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
Fixes mapping error.
:cl:
fix: Lavaland syndie base no-gravity spot fixed
/:cl:
> Lavaland Syndi-Base Area Fix

- code/controllers/subsystem/vote.dm
- config/config.txt
- config/splurt/maps.txt
- modular_splurt/code/controllers/configuration/entries/splurt_maps.dm
- tgstation.dme
Down with the box purgatory! This PR denies choosing the same map with every map vote. Yeah, I'm salty enough to add this in.
This PR **modifies a subsystem file.** This change is in the file itself to avoid having to copy/paste large swaths of code to a modular file. It's a total of four lines that were changed, and while this shouldn't cause many (if any) conflicts, it MAY cause them in the future. Coder beware.
Box gets kinda boring sometimes ngl.
Nah.
:cl:
tweak: Removed the ability to vote for the same map over and over. It's too OP.
/:cl:
> Maps 2 Electric Boogaloo

- _maps/map_files/PubbyStation/PubbyStation.dmm
Pipes in blueshield office and surrounding maint overlapped due to lack of tetris skills, issue is now fixed
:cl:
fix: Pipes area fixed
/:cl:
> Fixes the pipes in the Blueshield office

- code/game/objects/items/robot/robot_upgrades.dm
what it says on the tin
fixes #152
:cl:
tweak: the cyborg advanced plasma cutter is now under mining instead of "general"
/:cl:
> adv plasm cutter is now correctly classified

- modular_splurt/code/modules/cargo/packs/armory.dm
- modular_splurt/code/modules/cargo/packs/goodies.dm
- modular_splurt/code/modules/cargo/packs/misc.dm
- modular_splurt/code/modules/projectiles/guns/energy/lasers.dm
Priority update due to exploits. Even by an admin at this point.
A priority fix for several weapons due to an exploit spreading. This was suppose to be a slower update but now I have to prioritize this.
Several fixes from spelling glitches to the Captain's .45 being private purchase. I hate oversights.
No a fix
:cl: radar651
fix: fixes the Captain's .45 for being bought privately. This was going to be fixed later but its gotten out of hand.
spellcheck: The double barrel shotgun sharing the title with the sawed off in private purchase panel.
spellcheck: Fix a spelling mistake in the civilian energy gun.
/:cl:
> Pirority Fix for several weapons

- code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
- modular_splurt/code/modules/reagents/chemistry/reagents.dm
- tgstation.dme
This PR allows coders to FINALLY use a custom icon file for drinking glasses and shot glasses through the reagent definition. Why it wasn't like this already, I don't know. That icon file is a mess. Guh.
No effect on gameplay, but huge effect on our merge conflicts. Now there's a conflict in code instead of icons! Assuming they update the code, it's pretty unlikely to be updated beyond the change I already made here.
Not a port, it's going upstream later so expect to see it back here eventually
:cl:
fix: Glass icon files can now be defined by the reagent. Thank FUCK.
/:cl:
> Modularize drinking glass+shot glass icons

- modular_splurt/code/modules/food_and_drinks/recipes/drink_recipes.dm
changes both recipes for cum in a hot tub to a 2 1 1 ratio from originally a 2 1 0.1
It just makes the recipe cleaner and doesn't leave extra reagents in the glass
No
:cl: Halford Steel
tweak: tweaked the cum in a hot tub recipe
/:cl:
> makes drinks for degenerates cleaner

- modular_sand/code/modules/mining/equipment/kinetic_crusher.dm
Nerfs the Shambling Miner's Mask trophy so it can be now a cheaper and weaker version of the Colossus' Blaster Tubes.
Because yes, this trophy is very fucky, but also too very generous at giving easy extra melee damage for killing some lavaland miner hobo with the crushie so reducing the bonus melee damage seems reasonable.
No.
:cl:
balance: nerfed Mask of Shambling Miner's mask bonus melee damage from 10 to 5.
/:cl:
> [Semi-modular]Shambler mask nerf.

- modular_splurt/code/modules/mob/living/silicon/robot/robot_modules.dm
Cargo Clamp was already in-game, now Cargo Borgs have one.
Gives the Cargo Borg a Cargo Clamp
Allows Cargo Borgs to move crates easily
No
:cl:
add: Cargo clamp to Cargo Borgs
/:cl:
> Cargo Borg Cargo Clamp

- modular_splurt/code/game/object/items/stacks/tiles/tile_reskinning.dm
- modular_splurt/code/game/object/items/stacks/tiles/tile_types.dm
- tgstation.dme
No longer a hotfix! We've fully fixed borg tiles fucking dying, woo!
Borg tiles quit fucking dying
Nah fam
:cl:
del: The fucking stupidest bug ever for us engiborgs
fix: Borgs will no longer drop their floor tiles when they choose a different tile type
/:cl:
> Hotfix for borg tiles fucking dying

- code/datums/elements/flavor_text.dm
Title.
:cl:
qol: Ghosts can now bypass ANY requirement for seeing flavortext and OOC notes
admin: Staff when aghosting get the same things, so you can easily see peoples OOC notes if disputes come up, and they're in something that prevents examines.
/:cl:
> {TESTMERGE ONLY FOR NOW} Flavortext hide bypasses

- _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
- code/modules/smithing/anvil.dm
- code/modules/smithing/finished_items.dm
We do a bit of reworking.
:cl:
add: Smithing scaling mechanics! Better smiths actually make better gear...
fix: Lavaland Syndiebase now actually gets the correct boards to setup R&D.
fix: Artifact scaling was fixed.
tweak: Artifacts can now be made multiple times on the same anvil, without it being a debug.
add: Plant data disks to Syndicate lavaland's crates.
/:cl:
> {TESTMERGE ONLY} Smithing + Lavaland fixes and changes

- modular_splurt/code/modules/cargo/packs/misc.dm
- modular_splurt/code/modules/clothing/suits/miscellaneous.dm
Gives trencher's coats ability to put Det-tier items. This increases cost of the cargo's orders, however.
N/A (14 voted for, 3 against, at the time of edit)
Nope.
:cl: Anonymous
tweak: wip: Trencher's coats are now able to hold detective-tier items, however cargo costs for them are increased.
/:cl:
> Allows trencher's coat to hold some extra items (Suggestion 1913)

- modular_splurt/code/modules/jobs/job_types/psychologist.dm
title
teehee
No
:cl:
add: Adds "Rental Mommy" and "Rental Daddy" job names for psychologist
/:cl:
> Literally just a couple extra psychologist titles

- code/__SPLURTCODE/DEFINES/is_helpers.dm
- config/entries/donator.txt
- modular_splurt/code/_DEFINES/is_helpers.dm
- modular_splurt/code/modules/client/loadout/donator/first_tier.dm
- tgstation.dme
adds some more donator thingies
yes
No
:cl:
add: added two new items to the donator loadout, one of them being a portal fleshlight pack
/:cl:
> Another smol donator batch

- code/modules/mining/lavaland/necropolis_chests.dm
- modular_sand/code/modules/mob/living/simple_animal/hostile/megafauna/king_of_goats.dm
Added +10 damage to all of the hierophant clubs attacks and lowered their cooldown by a few seconds, this was needed as the hierophant club was hot ass previously.
Brought the King Goat to the vet and chipped him, he can now be found on any GPS with the "Regal Signal"
There's no downside to adding a GPS signal to king goat, just makes him a lot less annoying to find. The hierophant club was absolutely unusable in any lavaland fights, I didn't make it overpowered, just... Less unusable...
:cl: 567Turtle
add: King Goat GPS Signal (Regal Signal)
balance: Balanced the hierophant club so its now decent
:cl:
> Buffed Hiero Club, Chipped King Goat

- config/splurt/general.txt
- modular_splurt/code/controllers/configuration/entries/splurt_general.dm
- modular_splurt/code/controllers/subsystem/processing/station.dm
- tgstation.dme
idk why this wasn't added on upstream to begin with but yeah. Toggle it off and you'll not have random traits on next rounds
intern. voice.
No
:cl:
server: Adds a config to toggle random station traits each round on and off
/:cl:
> makes random station traits a config

- _maps/RandomRuins/SpaceRuins/spacehotel.dmm
title.
why hasnt this been done before
no?
:cl:
fix: hotel's pool is functional
/:cl:
> Makes the space hotel's pool functional.

- modular_splurt/code/game/object/items/implants/radio_implant.dm
- modular_splurt/code/modules/research/designs/medical_designs.dm
- tgstation.dme
This was bothering me. It was configured to hand out an item in an unusable state, and also had an item description inconsistency. I was somewhat surprised that the cased version of this implant did not exist already, since the item did. But I think I know why. My guess is that it only exists to be the parent class for the syndicate and radio capable mobs versions of itself. If it does something freaky, say so and someone will alter or remove it I guess. I did test it, it works exactly the way I would expect it to.
Bug fix is good.
Nope.
- 🗹 You tested this on a local server.
- 🗹 This code did not runtime during testing.
- 🗹 You documented all of your changes.
Tested it a couple times. Which is how I found I was missing the include. And the labeling inconsistency.
:cl:
fix: fixed the …
> [BUG FIX] lathe constructable radio implant fix

- _maps/map_files/Deltastation/DeltaStation2.dmm
• Fixes Delta arrivals being unpowered roundstart, bug introduced in #454 
• Rotates shower in Blueshield office that is hidden under the curtain, also #454 
Arrivals being powered good
Not a port!
:cl:
fix: Deltastation arrivals will no longer start disconnected from the grid.
/:cl:
> Delta Fixes - Arrivals APC & Blueshield Office

- code/__DEFINES/citadel_defines.dm
- code/__DEFINES/sound.dm
- code/__SPLURTCODE/DEFINES/cit_defines.dm
- code/__SPLURTCODE/DEFINES/sound.dm
- tgstation.dme
Moves 2 defines from modular Splurt define folders to their original folders. These two(for sounds I'm guessing!) need to be unique, and by moving them elsewhere you're just asking for odd bugs. Rather than spending a few minutes resolving merge conflicts you'll face hours of debugging.
> unmodularize 2 defines that need to be unique

- modular_splurt/code/game/object/items/implants/implant_gfluid.dm
- modular_splurt/code/game/object/items/implants/implantcase.dm
- tgstation.dme
Makes it so the fluid infuser implant is *actually emaggable*. Also adds in hacked versions of the fluid implant for ease of adminbus.
The emag action for the implant itself was already in the code, it was just unreachable due to the fact the implant itself was never an item one would see in-game, since it was always contained within either an implant case, implanter, or body. Now emagging an implant case containing the implant will call the emag action on the implant.
No.
:cl:
fix: made it so emagging an implant case containing the gfluid implant will call the emag function on the implant
add: pre-emagged variants of the implanter/implant case for adminbus
/:cl:
> Fix fluid infuser emagging action

- code/game/objects/items/stacks/bscrystal.dm
Adds proper scan_state for BS crystals, so they can be picked up on mining scanners.
:cl:
Fix: BS Crystals show up on mining scanners again
/:cl:
> Adds scan_state to bluespace crystals

- modular_splurt/code/modules/mob/dead/crew_manifest.dm
why did it take SO LONG until someone told me about this
woopsie
No
:cl:
fix: fixes borg's crew manifest because no one told me it was bugged until now
/:cl:
> Fix silicon crew manifest

- _maps/map_files/Deltastation/DeltaStation2.dmm
• Fixes dark spots in engineering due to lack of lighting.
• Removes junk-clutter in engineering and the CE's office.
• Second disposals bin for engineering, near the lathes. Mail sorting now goes to this bin.
• Autolathe in engineering, saves the manual task of removing the plasteel table and putting an autolathe there every shift.
• Power tool storage now has engineering access. It gets hacked into **every** round. That's it's only purpose. May as well skip the chore. It also has the welding tool too.
• Supermatter engine room has the scrubbers and supply piping moved out of the way to allow more modification to the default engine. Previously, a quarter to a third of the floorspace was taken up by air and scrubber pipes. Now it's kinda like a tenth at most.
• Gravity Generator access is …
> Deltastation Engineering QOL

- _maps/RandomRuins/StationRuins/Box/Engine/splurt/diy.dmm
- _maps/RandomRuins/StationRuins/Box/Engine/splurt/diy_sm.dmm
- config/entries/general.txt
- modular_splurt/code/datums/ruins/station.dm
• Adds in a DIY engine. It's a blank area filled with materials, stripped bare so it's ready for construction as soon as the round starts!
• Adds in a DIY supermatter engine. It's basically a supermatter in an empty blank room.
Replacement for getting rid of the PACMAN meme engine that's nothing but an annoyance for engineers and a kick in the balls for station crew when power runs out because the engineers have to spend thirty minutes ripping out the SMES unit.
Build-a-SM is something the moths will flutter like crazy over.
```
BOX_RANDOM_ENGINE Box SM,3
BOX_RANDOM_ENGINE Box Tesla,3
BOX_RANDOM_ENGINE Box Singulo,2
BOX_RANDOM_ENGINE Box SM 1x3,0
BOX_RANDOM_ENGINE Box SM 5x5,0
BOX_RANDOM_ENGINE Box SM 3x,0
BOX_RANDOM_ENGINE Box TEG,2
BOX_RANDOM_ENGINE Box Empty,0
BOX_RANDOM_ENGINE Box …
```
> New Boxstation random engines!

- modular_splurt/code/modules/mob/living/living.dm
- modular_splurt/code/modules/mob/living/silicon/pai/pai.dm
- modular_splurt/code/modules/mob/living/silicon/robot/robot.dm
- modular_splurt/code/modules/mob/living/simple_animal/simple_animal.dm
Verb to set gender for simple mobs and silicon+pAI is now call a shared proc instead of having major code copy-pasted to each related path. This is not very good attempt at "sharing" verb, but I cannot do it any better personally.
Note: Includes #568 changes (by @LunarFleet) along with @Zirok-BYOND edit suggestions.
Better code readability? idk
Not a port but (again) incorporates changes of #568 into proc edition.
:cl: Anonymous
code: Rewrites "Set Gender" for simple mobs and silicon as an upward proc for "mob/living", while makes previous verbs to call for the proc instead. While it'll help with verbs now sharing the same function (and thus easier to edit), I am not sure if it will help with duplicate code.
add: "Set Gender" menu (for silicon/simple mobs) now allow you to toggle breasts …
> A poor attempt to de-duplicate "Set Gender" verb code

- code/game/objects/items/stacks/sheets/leather.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- modular_sand/code/modules/vending/kinkmate.dm
Changes the leather and cloth crafting recipes to have both a loincloth with and without sensors. Also changes the loincloth in the kinkmate to have sensors.
Makes you not need to look for an autodrobe or have a loincloth in your loadout if you want to go a bit more tribal while retaining your suit sensors.
No
:cl:
qol: Makes loincloths with and without sensors craftable, makes the loincloth from the kinkmate have sensors.
/:cl:
> Changes loincloth crafting and kinkmate loincloth

- modular_splurt/code/datums/traits/good.dm
- modular_splurt/code/datums/traits/neutral.dm
does a second over of the traits files' grammar
look at a dictionary please
no
:cl:
spellcheck: traits
/:cl:
> traits grammar episode two

- modular_splurt/code/datums/traits/neutral.dm
just adds one period
it's just one period
no
:cl:
spellcheck: forgot a period
/:cl:
> adds a singular period

- code/modules/mob/living/say.dm
Updated russian localization to certain radio channels and some other chat's functions.
Keeping the code up-to date and fixes a bug for newly created ru-servers (lack of ability to say in radio without using english keyboard).
[Also I already merged it in /tg/station.](https://github.com/tgstation/tgstation/pull/56882)
:cl: SishTis
fix: Updated russian keyboard localization. You can now use russian letter as prefix for radio channel, like, :у for engineering.
/:cl:
> Updating russian localization

- code/modules/clothing/under/miscellaneous.dm
- modular_splurt/code/modules/clothing/under/miscellaneous.dm
Needing to adjust the harness every time is annoying, counterproductive, and confusing. This does not prevent adjusting it back to covering.
Reverts the default state of Gear Harness to not covering anything. It can still be adjusted normally.
Needing to manually adjust the gear harness every time is annoying, easy to forget, and confusing for people who don't know it can be adjusted.
No
:cl:
tweak: Gear harness starts in adjusted mode
/:cl:
> Make Gear Harness adjusted by default

- modular_splurt/code/modules/research/designs/mechfabricator_designs.dm
This PR is just a name change for the printable IPC brain. I have observed several cases of inexperienced roboticists not knowing what is and is not a usable positronic brain, so I have removed the word "positronic" from the one that does not go to borgs. This should hopefully reduce confusion and mistakes. I was going to remove it completely, but you can print non-functional brains from the limb grower, and it would be inconsistent to remove them here.
Also got the voice box. Did you know that IPC stands for Integrated Positronic Chassis? "IPC Positronic" is redundant anyway.
Reduces a source of OOC confusion.
Nope.
:cl:
qol: removed the word "positronic" to reduce the number of items called this in the exosuit fab
/:cl:
> Reduces a source of confusion with positronic brains

- modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
_Originally suggested by Average Water Enjoyer#5949, but adjusted for consistency._
Adds a job-slut title for all medical jobs
Allows the medical team to ~~ignore their jobs and~~ be even more horny.
No.
:cl:
add: Added new job title for Chief Medical Officer: Chief Medical Slut
add: Added new job title for Medical Doctor: Medi-Slut
add: Added new job title for Paramedic: Para-Slut
add: Added new job title for Psychologist: Psycho-Slut
add: Added new job title for Chemist: Chemi-Slut
add: Added new job title for Virologist: Viro-Slut
add: Added new job title for Geneticist: Geneti-Slut
/:cl:
> New slut-type job titles for medical

- modular_splurt/code/datums/traits/negative.dm
- modular_splurt/code/datums/traits/neutral.dm
- modular_splurt/code/modules/clothing/masks/gasmask.dm
Under the precedent that mood quirks should be neutral, this commit makes the following changes;
- Adds a new cosmetic-only gas mask variant
- Bane Syndrome is now neutral, worth 0 points
- Quirk grants the new non-functional gas mask instead of a regular one
Wearing a mask is mechanically beneficial. Some jobs - like shaft miner - even require it. Granting both quirk points and a mood bonus for something advantageous, simple, and often required allows for easy power-gaming.
No.
:cl:
tweak: Converted Bane Syndrome quirk to neutral
tweak: Bane Syndrome starts with a non-functional mask
/:cl:
> Nerf Bane Syndrome quirk

- modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
- modular_splurt/code/modules/jobs/job_types/peacekeeper.dm
Adds the titles "Hired Muscle" and "Bodyguard" to Peacekeeper.
_Originally requested as a job by LISKO FLEXIT ALLE#0085
Requested as job titles by ReturnToZender#3590_
Adds a new title-based roleplay opportunity.
No.
:cl:
add: Added new job titles for Peacekeeper: Bodyguard, Hired Muscle
/:cl:
> Add two new Peacekeeper titles

- modular_splurt/code/modules/client/loadout/socks.dm
Title
Yes
No
:cl:
add: Added garters to the loadout
/:cl:
> Add garters to the loadout

- modular_splurt/code/modules/mob/splurt_emotes.dm
Adds facepalm, facepaw, faceclaw, and facehoof. Displays a random message from three possibilities, and plays the slap sound. Exemplified below.
- "crewmate places their hand across their face."
- "crewmate lowers their face into their claw."
- "crewmate facepaws"
Facepalm and facepaw are (or were) common expressions used online to express emotion.
No.
:cl:
add: Added metacarpus emotes: Facehand, facepaw, faceclaw, and facehoof
/:cl:
> Adds face-metacarpus emotes

- modular_splurt/code/modules/mob/mob_helpers.dm
- tgstation.dme
Allows players with the Empath or Friendly quirk to detect when another player has the Distant or Headpat Slut quirks.
_Originally suggested by Average Water Enjoyer#5949
Modified to also allow detecting Headpat Slut_
Quoting the original request:
_"Friendly characters are more likely to use the 1 positive point they used that doesn't benefit them at all but benefit others to headpat and hug people. Funny mood boosts. This gives them a tell on who doesn't want to be headpatted."_
\- Average Water Enjoyer#5949
Not having a tell for who doesn't want to be touched causes awkward interactions, and sometimes (5% chance) triggers an attack action. Adding an additional tell for people who requested (via quirk) to be touched also made logical sense.
No.
:cl:
tweak: Empath and Friendly crew can …
> Allow empath to detect Distant and Headpat Slut

- modular_splurt/code/modules/vending/kinkmate.dm
Invisible shoes are currently only obtainable by loadout. Forgetting to select them, or losing them during the round, would them unobtainable before this change. They're added to Kinkmate to match the Gear Harness placement, as the two items serve a similar purpose.
_This should've been in the original PR, but I forgot._
Makes a cosmetic item available without needing to respawn. Helpful when dying to a freak science accident and losing your shoes.
No.
:cl:
tweak: Invisifiber Footwraps can be purchased from the Kinkmate vendor
/:cl:
> Add Invisiber Footwraps to Kinkmate vendor

- code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
- code/modules/reagents/chemistry/reagents/other_reagents.dm
- modular_splurt/code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
- modular_splurt/code/modules/reagents/chemistry/reagents/other_reagents.dm
- tgstation.dme
Moves TRAIT_CURSED_BLOOD effects into modular code space, and slightly re-formats the code for better readability. Makes change to holy water reagent and blood drunk miner mob.
Following modularity standards is good.
No.
:cl:
refactor: Modularized cursed blood effects
/:cl:
> Modularize cursed blood effects

- code/game/machinery/computer/communications.dm
Fixing "Buy slaves" button on communication console. It was broken due to code merge, making unable to pay money for slaves.
* Slavers now can sell their slaves
No
:cl:
fix: "Buy slaves" button on communication console fixed 
/:cl:
Thanks to Crowbar764 for detecting that problem!
> Fixing "Buy slaves" button on communication

- modular_splurt/code/modules/awaymissions/mission_code/academy.dm
- tgstation.dme
Allows the dice to be rolled once per user, instead of once ever. Completely prevents running the roll function when a user is disallowed.
Allows bringing back and sharing a rare fun item with other users, but without the ability to spam it. Also reduces confusion for why effects aren't triggering on one-use dice.
No.
:cl:
tweak: Dice of Fate is now usable once per-person
/:cl:
> Per-person single-use Dice of Fate

- modular_splurt/code/datums/ai_laws.dm
rewrites horny ai laws
makes them look nice
no
:cl:
spellcheck: horny ai laws
/:cl:
> rewrites horny ai laws

- modular_splurt/code/datums/components/pregnancy_inert.dm
deleted component/ovipositor/egg_type couse it cant properly take egg_type from client (him just not in there in time component generating), and changed it on always check players pref before cum (like experience component/pregnancy in lay_eg)  
fix bug there inert egg always was chicken type regardless of the pref choice. 
:cl:
fix: fixed inert egg was always has chicken egg sprite regardless of the pref choice. 
/:cl:
> fix inert egg always was base chicken egg

- modular_splurt/code/game/objects/items/implants/implant_gfluid.dm
Updates the fluid infuser implant to use an action datum button instead of the standard implant button. Also fixes a typo, adds more comments, and updates variable name readability.
Action datums look nicer, and provide more information to the end user.
No.
:cl:
tweak: Fluid Infuser implant uses an improved activation button
/:cl:
> Update Fluid Infuser button

- modular_splurt/code/modules/mob/living/carbon/carbon.dm
- modular_splurt/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Updates Liquid Panty Dropper with the following:
- Ignores held items
- Only plays rip noise once
- Displays a different chat message for the target user
- Items are thrown, instead of dropped
- Moves functional code from alcohol reagents to a mob proc
- - This change is made so other items can use the effect
- More comments!
The main purpose of this change is facilitate other items using LPD effects.
No.
:cl:
tweak: Liquid Panty Dropper now launches clothing
tweak: Liquid Panty Dropper no longer interferes with held items
code: LPD's clothing burst is now a mob proc
/:cl:
> Update LPD drink effects

- modular_splurt/code/modules/cargo/packs/misc.dm
- modular_splurt/code/modules/reagents/reagent_containers/bottle.dm
Adds the new Plushmium Crate to cargo, which contains a bottle of Plushmium and a plushie choice box. Also adds an item for the Plushmium Bottle, so it can be in the crate.
_Originally requested by Toast#8706 on Discord, in Suggestion #3839._
Facilitates some users _specific interests_ without reliance on a chemist player's cooperation.
No.
:cl:
add: Added a Plushmium Crate to cargo
/:cl:
> Adds a Plushmium Crate

- code/game/objects/items/devices/PDA/cart.dm
- modular_splurt/code/game/objects/items/devices/PDA/radio.dm
- tgstation.dme
Self explanatory, added chemwhiz chemical lookup function to med-u deluxe.
CMO can be a better chemist, removes the need to switch between the ChemWhiz cartridges and the Med-U DELUXE
no.
:cl:
add: Added CART_CHEMISTRY access to cart-cmo
/:cl:
> chemistry access added to Med-U DELUXE cartridge

- modular_splurt/code/game/objects/items/storage/boxes.dm
- modular_splurt/code/modules/cargo/packs/misc.dm
- modular_splurt/code/modules/reagents/reagent_containers/bottle.dm
- modular_splurt/code/modules/reagents/reagent_containers/spray.dm
This PR incorporates user feedback for https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/676.
- Reduces the amount from 30 to 5
- - Allows converting only one plushie per shipment
- Replaces the bottle with a single-use a spray bottle variant
- Prevents using the spray bottle on non-plushies
- Adds a boxed set for the items
- Adds an explanatory lore note to the box set
- Updates shipment information
The original was intended to convert one plushie per shipment, but was mistakenly set too high. In addition, users could become confused at the item's intended usage, and accidentally waste it.
No.
:cl:
add: Added the Love to Life spray bottle
tweak: Updated Plushmium Crate contents
/:cl:
> Plushmium crate improvements

- modular_splurt/code/game/objects/structures/pole.dm
Adds a simple range check.
Resolves: https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/issues/512
Teleporting is baaad.
:cl: Casper
fix: fixes telekinetic users from teleporting to stripper poles
/:cl:
> Bugfix: Stops telekinetic users from teleporting to poles.

- code/game/objects/structures/electricchair.dm
- code/modules/assembly/shock_kit.dm
- Fixes self-attack shock component runtime.
- Fixes map-spawn electric chair infinite metal exploit.
Map-spawned e-chairs are created without a shock component, thus runtime during deconstruction.
Resolves: https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/issues/671
Less runtimes.
:cl: Casper
fix: infinite metal exploit
/:cl:
> Bugfix: Infinite metal.

- modular_splurt/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Updates Liquid Panty Dropper's drink effect to check the client's preferences for ERP and aphrodisiacs before triggering. Setting either to disabled will return with no effect.
Mitigates the effects non-consensual drink spiking and chem flooding. While this does not account for more nuanced preferences, it can eliminate some unwanted cases.
No.
:cl:
tweak: Liquid Panty Dropper now checks client prefs
/:cl:
> Check client prefs before triggering LPD drink

- modular_splurt/code/game/objects/items/storage/boxes.dm
- modular_splurt/code/modules/client/loadout/backpack.dm
- modular_splurt/code/modules/vending/kinkmate.dm
Adds a box of ten condoms to the kinkmate vendor. The item is priced at half the cost of buying them individually. Also added to the loadout screen, under the backpack tab.
_Created to address Suggestion 112 by Discord user Remi_Scuntlet#5535_
Increases opportunities for the crew to practice safe and responsible interpersonal relations. Users expressed a desire for additional stock of this item.
No.
:cl:
add: Added a surplus condom box to Kinkmates
/:cl:
> Adds the surplus condom box

- modular_splurt/code/datums/mood_events/drug_events.dm
- modular_splurt/code/datums/mood_events/generic_negative_events.dm
- modular_splurt/code/datums/mood_events/generic_positive_events.dm
- modular_splurt/code/datums/mood_events/needs_events.dm
- modular_splurt/code/datums/mood_events/preg_events.dm
Restores missing newline markers to modular mood events. These were lost during a replacement of HTML spans. Also adds the missing span to mood event `cum_craving`.
Fixes a code error regression.
No.
:cl:
fix: Fixed missing newline characters for mood events
/:cl:
> Fix mood event newlines

- Build.bat
- modular_splurt/code/game/objects/items/robot/robot_items.dm
- modular_splurt/code/modules/mob/living/silicon/robot/robot.dm
- modular_splurt/code/modules/mob/living/silicon/robot/robot_modules.dm
This allows service cyborgs to cook, and it also allows other types of borgs to use the crafting menu. 
Service borgs are near utterly unused, as all they really do is... clean floors and pour drinks; now, they can cook too, which will hopefully make them a bit more enticing. Furthermore, giving engineering borgs the crafting menu allows them to make previously inaccessible structures/furniture!
No
:cl:
tweak: Allowed borgs to craft
tweak: Changes service borgs' items
/:cl:
> Allow service borgs to cook

- code/__SPLURTCODE/DEFINES/zeros/traits.dm
- code/game/machinery/computer/cloning.dm
- modular_splurt/code/datums/traits/negative.dm
Removes the quirk DNC from the code, as it was made redundant by an upstream merge, containing an important exploit fix.
The upstream PR can be found here: https://github.com/Sandstorm-Station/Sandstorm-Station-13/pull/293.
Removes obsolete redundant code.
No.
:cl:
code: Removed redundant definition of DNC quirk
/:cl:
> Remove redundant use of quirk DNC

- modular_splurt/code/modules/mob/living/silicon/robot/inventory.dm
Adds more booze options to the Service Borg Booze Shaker, for your bartending pleasures
Adds a few missing Booze options to the Service Borg Booze Shaker
Several drinks could not be made by Borgs, this aims to fix that.
No
:cl:
tweak: Modified Booze Shaker options
/:cl:
> Borg Beer Shaker drink add

- modular_splurt/code/game/objects/items/lewd_items/genital_equipment/condom.dm
- modular_splurt/code/game/objects/items/storage/boxes.dm
This PR will do the following:
- Set a price for the condom item: 10 credits (PRICE_CHEAP_AS_FREE)
- Reduce the set price for the surplus condom box: 80 credits (PRICE_BELOW_NORMAL)
_Addresses Suggestion #3984 by Discord user Remi_Scuntlet#5535._
Makes a roleplay-oriented item more affordable for crew with low paying jobs, including Assistants. Primarily meant to address user feedback.
No.
:cl:
balance: Reduced the price of individual condoms from 40 to 10 credits
balance: Reduced the price of bulk condoms from 200 to 80 credits
/:cl:
> Reduce condom prices

- code/__SPLURTCODE/DEFINES/zeros/traits.dm
- code/modules/mob/living/carbon/examine.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
- modular_splurt/code/datums/traits/neutral.dm
- modular_splurt/code/modules/reagents/chemistry/reagents/drug_reagents.dm
Removes quirks In Heat and Estrus Detection, which were merged upstream in https://github.com/Sandstorm-Station/Sandstorm-Station-13/pull/298.
These features were originally ported to this codebase in PR https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/20 by GitHub user @NullFag, who would prefer to be credited for doing so.
Removes content that was made obsolete by an upstream merge.
No.
:cl:
code: Removed obsolete entries for In Heat and Estrus Detection
/:cl:
> Remove obsolete Heat quirks

- code/game/machinery/computer/arcade.dm
- modular_splurt/code/game/objects/items/miscellaneous.dm
- modular_splurt/code/game/objects/items/toys.dm
Adds two new toy items that grant role-play-oriented brain traumas. Both can be earned as prizes from the arcade machine, and are single-use. Item flavor text is updated after use to indicate their status.
Items and associated traumas are:
- Imaginary Friend Action Figure: Imaginary Friend
- Dissociative Mirror: Split Personality
_Created in response to Suggestion #3844 by Discord user Hen 101#6765._
Adds a more reliable method for obtaining brain traumas that create new unique social opportunities. Items should be uncommon enough to prevent spam usage.
No.
:cl:
add: Added the Imaginary Friend Action Figure
add: Added the Dissociative Mirror
/:cl:
> Add roleplay brain trauma toys

- modular_sand/code/modules/research/designs/machine_designs.dm
- modular_sand/code/modules/research/techweb/nodes/bluespace_nodes.dm
Uncomments the techweb node and machine design for crypto miners. This is in response to Suggestion #3951 by Discord user legume#4970.
Prevents cargo from needing to gamble for crypto miner boards later into the round, and reduces the annoyance of farming random crates. Cryptominers were balanced around being easily obtainable, but difficult to run.
No.
:cl:
tweak: Restored techweb node and circuit printing for Cryptominers
/:cl:
> Revert non-modular removal of cryptominers

- modular_splurt/code/modules/keybindings/keybind/communication.dm
- modular_splurt/code/modules/mob/say_vr.dm
- tgstation.dme
This commit adds a variant of the subtle verb that uses a typing indicator, and replaces the original key binding with it. Does not attempt to fix unrelated cyborg overlay issues.
Replaces https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/489.
Replaces an existing test-merged PR with better code.
No.
:cl:
add: Added variant of Subtle verb with typing indicator
tweak: Default binding for Subtle is now Control-5
/:cl:
> Add variant Subtle verb with typing indicator

- modular_splurt/code/datums/interactions/lewd/lewd_datums.dm
Bounty related to: https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/issues/735
A new feature!
No.
- [Yes ] You tested this on a local server.
- [Yes ] This code did not runtime during testing.
- [Yes ] You documented all of your changes.
:cl:
add: Adds the inflate verb.
/:cl:
> bounty inflate belly verb

- modular_splurt/code/modules/clothing/under/miscellaneous.dm
srry, missed the digitigrade flag thing
digitigrade>>>>>>
N
:cl:
fix: Space princess outfit now can be used along with digitigrade legs
/:cl:
> space princess digitigrade flag

- modular_sand/code/game/machinery/computer/arcade/tetris.dm
This commit reverts non-modular edits to the TETRIS arcade machine to maintain parity with upstream edits.
Upstream PR can be found here: https://github.com/Sandstorm-Station/Sandstorm-Station-13/pull/300
Changes made in this repository have been rendered obsolete by upstream changes. Reverting these changes will allow for cleaner merging.
No.
:cl:
code: Reverted non-modular SPLURT edits to TETRIS
/:cl:
> Revert non-modular TETRIS edits

- modular_splurt/code/modules/reagents/chemistry/reagents/drug_reagents.dm
This PR does the following:
- Adds In Estrous quirk removal effect to Hexacamphor
- Adds preference-related failure event logging to Hexacrocin and Hexacamphor
- Checks for quirk instead of trait
This will accomplish the following:
- Allow removing the otherwise permanent quirk assignment caused by Hexacrocin
- Allow admins to check logs for potentially unwanted usage of Hexa-chems
While non-consensual use of these chemicals is an admin issue, having an in-character method of counteracting negative effects is helpful for when admins are unavailable, or for users who would prefer to resolve cases in-character.
No.
:cl:
tweak: Hexacamphor overdose will remove the In Estrous quirk
/:cl:
> Minor Hexa-chem overdose improvements

- modular_splurt/code/modules/research/techweb/nodes/nanites_nodes.dm
- tgstation.dme
Prevents researching the Infective Exo-Locomotion nanite type, listed in the techweb as `spreading_nanites`, due to conflicts with server rules. This is done with a modular techweb node removal edit.
Replaces https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/757
Prevents users from obtaining a nanite program that is prohibited from use by server rules, without making non-modular edits.
No.
:cl:
del: Removed techweb entry for Infective Exo-Locomotion nanites
/:cl:
> Prevent researching Infective Exo-Locomotion

- code/__SPLURTCODE/DEFINES/quirks.dm
- code/__SPLURTCODE/DEFINES/species.dm
- code/__SPLURTCODE/DEFINES/traits.dm
- code/__SPLURTCODE/DEFINES/zeros/species.dm
- code/__SPLURTCODE/DEFINES/zeros/traits.dm
- modular_splurt/code/datums/traits/neutral.dm
- tgstation.dme
Moves all trait definitions into a single file, fixes inconsistent capitalization, and sorts them into even lists by type. Does the same for species defines. Also removes mood category variables, and replaces them with defines.
Reduces potential confusion and inconsistency when adding new traits, and may help to reduce merge conflicts from pull requests that add new traits. Mood categories were better set as defines, as they will never change.
No.
:cl:
refactor: Refactored trait defines
/:cl:
> Refactor trait defines

- config/splurt/autocryo.txt
- modular_splurt/code/controllers/subsystem/afk.dm
- modular_splurt/code/modules/mob/living/logout.dm
This PR does the following
- Adds logging for when a mob isn't added to the auto-cryo list
- Adds an exclusion condition for dead mobs
- Changes list length checking method to `LAZYLEN`
- Fixes a typographical mistake in configuration text ("seconds" to "ticks")
Adds more logging for admins, and prevents cases potential cases of unwanted automatic body disposal services.
No.
:cl:
tweak: Auto-cryo now ignores dead bodies
admin: Auto-cryo now logs all cases of mobs being ignored
/:cl:
> Minor auto-cryo improvements

- modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
This commit adds more alternate titles for jobs.
Scientist:
- Nanite Programmer
- Tetromino Researcher
Prisoner:
- Low Security Prisoner
- Medium Security Prisoner
- Maximum Security Prisoner
- Supermax Prisoner
- Protective Custody Prisoner
- Prison Slut
Roboticist:
- MOD Mechanic
Cargo
- Cryptocurrency Technician
_Addresses Suggestion #4142 by Gmgaraz#4289 - Prisoner job titles
Addresses Suggestion #4139 by Tony Meowprano#2038 - Nanites job title_
Adds more ways to describe a character's job on the station.
No.
:cl:
add: Added new scientist job titles: Nanite Programmer, Tetromino Researcher
add: Added new roboticist job titles: MOD Mechanic
add: Added new prisoner job titles: Low Security Prisoner, Medium Security Prisoner, Maximum Security Prisoner, Supermax Prisoner, Prison Slut
add: …
> Add more assorted job alt titles

- modular_sand/code/modules/mob/living/silicon/robot/robot_modules.dm
Basically this is a simple PR removal of the duplicated mining points card.
Annoyingly unnecesary to have two mining points cards.
It was in the sandstorm's modular codes.
:cl:
del: Removed duplicated mining points card.
/:cl:
> Removes duplicated mining points card from Minerborg.

- _maps/RandomZLevels/away_mission/Academy.dmm
- code/game/machinery/cryopod.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/ruins/objects_and_mobs/sin_ruins.dm
- modular_splurt/code/modules/jobs/job_types/blueshield.dm
- modular_splurt/code/modules/jobs/job_types/bridgeofficer.dm
Changes the cryo messages for heads of staff and AIs, removing the need for them to ahelp.
Changes BO & BS greetings messages when arriving onto the station to more fit their roles.
Removes Die of Fate from lavaland ruin and academy, replacing them with a normal d20. You now have one extra dice for DND.
Messages fixes, and greetings tweaks are just generally good with no drawbacks. The die of fate was causing trouble, especially when it can give wizard which has multiple destroy round buttons.
Nyo
:cl:
del: Removes Die of Fate from Academy
del: Removes Die of Fate from Greed Ruin
tweak: BO and BS arrival on station messages are now more fitting
fix: Head of Staff and AI cryo messages no longer say you need to ahelp
/:cl:
> Cryo messages fixes, BO & BS greetings tweaks, Die of Fate is kill

- config/splurt/general.txt
- modular_splurt/code/controllers/configuration/entries/splurt_general.dm
- modular_splurt/code/modules/mob/mob.dm
People have been complaining about the locks since their introduction, so this pr should fix the issue.
suggested by MANY people, the locks system seems to be poorly received by players
no
:cl:
balance: Removes the locks on protolathes and other machines
balance: Well actually makes it a config but it's set to disable the locks so potato tomato
/:cl:
> Removes access lock from protolathes and other machines

- code/game/objects/structures/mirror.dm
- code/modules/client/preferences.dm
- code/modules/mob/living/carbon/human/innate_abilities/customization.dm
- config/splurt/general.txt
- modular_citadel/code/modules/client/preferences_savefile.dm
- modular_splurt/code/controllers/configuration/entries/splurt_general.dm
- modular_splurt/code/modules/client/preferences.dm
Title
bigger color customization range
No
:cl:
config: Makes character color limits a config (so you can make darker characters now)
tweak: select full black for default species color, select it again for full black
/:cl:
> Makes character color limits a config

- modular_splurt/code/modules/client/loadout/head.dm
Adds the decker headphones to the loadout selection (head slot).
Decker headphones are cool and some people (like me) might want to spawn with and customize them.
Not a port.
:cl:
add: Adds decker headphones to the loadout selection.
/:cl:
> Adds decker headphones to the loadout selection.

- modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
There is issue, that "Custodian" showed up as "misc" job in the manifest, as well causing issue with HUD icon and ID. This is due "Custodian" actually being a title for the ERT Janitor.
This PR replaces it with "Custodial Technician" instead.
Less issues.
Nope.
:cl: Anonymous
fix: Renames "Custodian" alt title into "Custodial Technician". This will fix ID, Manifest and HUD icon issues.
/:cl:
> [MODULAR] Renames Custodian into Custodial Technician

- modular_splurt/code/modules/mob/dead/new_player/sprite_accesories/tails.dm
Allows humans to have the Demon Spade tail.
Some guy on Discord asked for this and I want it now too.
Not a port.
:cl:
add: Allows humans to have Demon Spade tail.
/:cl:
> Allows humans to have Demon Spade tails.

- code/modules/admin/verbs/SDQL2/SDQL_2.dm
Ports over https://github.com/tgstation/tgstation/pull/76276, thanks to https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/issues/883 for letting us know
less exploits is always more safety
https://github.com/tgstation/tgstation/pull/76276
:cl:
admin: adds a safety prompt before running sdql commands
/:cl:
> Require affirmative input from the admin to run sdql2 verbs

- code/datums/elements/flavor_text.dm
- modular_splurt/code/datums/elements/flavor_text.dm
- tgstation.dme
Makes OOC notes visible even when face is covered
Avoids pre-breaking problems 
nope
:cl:
tweak: Modified flavor_text.dm to make OOC notes always visible
/:cl:
> OOC always visible

- code/modules/surgery/organs/stomach.dm
Makes vomiting from disgust clear 10 disgust.
Currently, vomiting causes a number of issues, most notably stun.  It does not, however, clear any disgust from the user.
Disgust can reach 150 or above, and the threshold for vomiting is 50. It only clears at 0.5 per tick and does not seem easily modified. 
The end result of this is that high levels of disgust will frequently cause people to empty their stomachs and then continue dry heaving for an extremely long time.
This helps it clear more quickly from high levels, 
Not ported.
:cl:
add: disgust vomiting makes characters less disgusted.
/:cl:
> Makes vomiting clear some disgust

- code/controllers/subsystem/jukeboxes.dm
- config/splurt/general.txt
- modular_splurt/code/controllers/configuration/entries/splurt_general.dm
So, last time a more automated way of adding songs to the jukebox was attempted (https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/891) it had unforseen consequences due to how byond's rsc system works. Most notably, these consequences were:
- Massive amounts of lag deep into the round
- RSC downloads eventually going past 600 mb
- frank sinatra fnaf 1 song being played every minute (very good song btw)
This attempts to make jukebox suggestions more optimized agan, but taking a different approach at it.
This pr works in tandem with https://github.com/SPLURT-Station/Mal0-cogs/pull/7, allowing players to suggest songs like they'd do with the suggestions command, and then letting admins review them and accept them if they feel those suggestions are good, or rejecting them …
> (Almost) Any song in the jukebox, take two

- modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
I cannot even.
Forgot the letter.
:cl:
spellcheck: Xenoarchaeolgist -> Xenoarchaeologist. Someone was drunk while adding it.
/:cl:
> Spellchecks Xenoarchaeologist because uhhhhhhhh

- code/__SPLURTCODE/DEFINES/traits.dm
- modular_splurt/code/datums/traits/good.dm
- modular_splurt/code/datums/traits/neutral.dm
- modular_splurt/code/datums/traits/trait_actions.dm
- modular_splurt/code/modules/mob/living/carbon/human/species.dm
Makes Radfiend function more similar to full radiation immunity (while still allowing for contamination, and the consequences therein). Keep in mind, as is stated in a file; that rads can STILL kill someone if they have this... It just takes near-fusion levels.
Also makes a separate perk to maintain the Radfiend glow for no cost or advantage.
The Undead, and anyone with the undead trait are already immune to rads, and that is a COMPLETELY FREE thing. Their only downside is being unable to use meds - which is... entirely negatable with just self-surgery to tend wounds. This puts Radfiend back to where it should have been, increases its cost - and generally allows a tad more of a glow.
Plus, considering how often admins/staff already hand out similar stuff for personal projects, this just …
> Radfiend Adjustments

- config/splurt/autocryo.txt
- modular_splurt/code/controllers/configuration/entries/splurt_autocryo.dm
- modular_splurt/code/controllers/subsystem/afk.dm
- modular_splurt/code/modules/mob/dead/observer/logout.dm
- modular_splurt/code/modules/mob/dead/observer/observer.dm
- tgstation.dme
Currently, ghosts that people leave after cryoing are left spawned in game generally for the rest of the round unless they decide to respawn to lobby. This causes ghost mobs to pile up around cryopods and other places which, as with every mob spam, might or might not cause performance issues as the round progresses
This pr makes it so the autocryo system currently in place also checks for ghosts that have been disconnected for a certain amount of time, and deletes their ass to improve performance. Of course, this function is configurable and toggleable.
Maybe improves performance yippee
No
:cl:
experiment: makes the autocryo subsystem delete ghosts that have been disconnected for a certain amount of time
/:cl:
> Makes the autocryo subsystem check for diconnected ghosts too

- code/__DEFINES/citadel_defines.dm
- code/__SPLURTCODE/DEFINES/traits.dm
- code/modules/client/preferences.dm
- modular_sand/code/datums/components/interaction_menu_granter.dm
- modular_splurt/code/datums/traits/neutral.dm
- modular_splurt/code/modules/arousal/organs/breasts.dm
- modular_splurt/code/modules/arousal/organs/penis.dm
- modular_splurt/code/modules/arousal/organs/vagina.dm
- tgui/packages/tgui/interfaces/MobInteraction.tsx
Added new trait called Messy. It bypasses checks for size when determining when checking if player can cover items with their cum.
Added preference toggle if someone doesn't like getting covered in cum.
More options is good! It's fun to cover stuff with cum but not everyone wants to have a giant shaft just to do it.
Not a port! Original. No steal.
:cl:
add: Added Messy trait, allowing you to cover stuff with cum while not meeting size requirements.
expansion: added new preference "Recieve cum covering", in case you don't want to be painted white.
/:cl:
> Adding Messy trait, Pref for getting splashed with cum

- _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
removes the one single explosive wall in the lavaland syndicate base experiment chamber
>make potassium water bomb
>throw it into the test chamber
>station gets nuked
this prevents that
:cl:
del: removes wall
/:cl:
> Removes the explosive wall in the syndicate lavaland base testing chamber

- modular_citadel/code/modules/client/loadout/mask.dm
- modular_splurt/code/modules/client/loadout/mask.dm
- tgstation.dme
exactly what the title says, only one line edited
because the default gas mask, not the atmos one, that you can easily get by either having bane syndrome or walking 5 tiles from your spawn and opening a firelocker, should not be restricted to engineering.
:cl:
tweak: makes the gas mask in loadouts no longer restricted
/:cl:
> Makes the default loadout gasmask not be restricted to engineering

- modular_splurt/code/datums/traits/neutral.dm
- modular_splurt/code/modules/client/loadout/mask.dm
Due `H.equip_to_slot` forces aesthetic gas mask onto mask slot, it also removes loadout mask. This PR fixes the issue by using `H.equip_to_slot_if_possible` instead for the quirk, making the aesthetic drop onto floor while character get their mask of choice.
Also, sorry K4rlox, but I changed your file to have proper indentation.
Bane/Gasmask Mooks will no longer suffer for being forced to wear aesthetic gasmask, even when they pick the liberated one from the loadout.
:cl: Anonymous
fix: Fixes Bane Syndrome quirk overwriting loadout's masks. Now the mask from the quirk will be dropped onto floor if you use loadout one.
/:cl:
> A workaround to fix loadout masks getting removed due Bane Syndrome quirk

- modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
- modular_splurt/code/modules/jobs/job_types/blueshield.dm
- modular_splurt/code/modules/jobs/job_types/bridgeofficer.dm
Adds a few more horny/lewd alt titles, mostly regarding the breeding caste. Actually wanted to fulfil the Suggestion 5351 regarding "bluesl*t", but went too far.
:cl: Anonymous
add: A bit more horny alt titles because we clearly don't have enough.
/:cl:
> A few more horny alt titles

- modular_splurt/code/modules/cargo/packs/misc.dm
- modular_splurt/code/modules/client/loadout/mask.dm
- modular_splurt/code/modules/clothing/masks/gasmask.dm
- modular_splurt/code/modules/clothing/suits/miscellaneous.dm
This will add glass gas mask and stripped/basic trencher gas mask into loadout. Trencher's especially since ~~nobody~~ rarely someone will hack the Clothesmate just to get that mask.
With that said, normal trencher gas mask is now named `"operative trencher gas mask"`, while the stripped version is just `"trencher gas mask"`. Also allows trencher coat to hold toys!
Felt like it would be neat for loadout to have alternative-looking gas masks.
Nope.
:cl: Anonymous
add: Added glass gas mask into loadout.
tweak: Renames trencher gas masks around: "trencher gas mask" -> "operative trencher gas mask" and "stripped trencher gas mask" -> "trencher gas mask", also modifies description. Otherwise, values are unchanged.
add: With that said, added trencher gas mask into loadout. You can still acquire …
> Adds glass gas mask and (stripped) trencher gas mask to loadout, plus renames

- code/game/objects/structures/crates_lockers/closets/genpop.dm
hooray
critical security fix :3
no
:cl:
fix: EZfix: Sanitises prisoner names on old lockers.
/:cl:
> yippee - I spent 2 hours looking for security exploits

- modular_splurt/code/_globalvars/lists/character_directory.dm
- tgui/packages/tgui/interfaces/CharacterDirectory.js
This adds `-pref` ERP Tags variants for Top and Bottom, as well as two paradoxic tags - `Dominant Bottom` and `Submissive Top`.
I used more direct wording instead of "Power Bottom" or "Service Top" since not everyone may know what they mean, and (I think) they are ~~(or were)~~ mostly used for MxM dynamics. I can change it to these instead if so desired by community / staff.
some luv for the power bottom and service top lovers goddammit
Nope.
:cl: Anonymous
add: Added ERP Tags for Character Directory: "Top-Pref", "Bottom-Pref", "Submissive Top", "Dominant Bottom".
/:cl:
> New, (rather) specific ERP Tags for Character Directory

- _maps/map_files/BoxStation/BoxStation.dmm
- code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
- code/modules/clothing/suits/miscellaneous.dm
- code/modules/research/designs/biogenerator_designs.dm
- modular_sand/code/modules/research/designs/biogenerator_designs.dm
Fixes the piping in Boxstation's sec because there was a scrubber that didn't work due to lack of a pipe. Also helps save me from my OCD because for some reason the ash "bottle" is just 10u of ash and EnduroGrow and Liquid Earthquake are dispensed in 30 units instead of 10.
Also adds a balloon message to the atmos heaters because for some reason only the freezers got them.
Also also fixes the suit for the wet floor sign worn as a suit on digi legs (no warranty for it looking fucky okay)
My OCD is fixed. Also helps save my engi ass the next time there's a pyro anomaly in the transfer center on box.
No.
:cl:
tweak: Biogenerator no longer triggers my undiagnosed OCD.
fix: Fixes a scrubber in Boxstation's security.
/:cl:
> Bunch of small fixes that keeps growing.

- modular_splurt/code/modules/jobs/job_types/peacekeeper.dm
Overpowered weapon removed from what is supposed to be a hall monitor.
Simply removes the choice of getting the telescopic baton (which is supposed to be reserved only for heads)
> Remove telescopic baton from peacekeeper loadout selecton

- code/modules/research/designs/mod_designs.dm
Fixes a wrong research icon state, which potentially triggered integration test errors.
Fix error = good.
Nope!
:cl:
fix: Wrong icon state triggering annoying errors in pull requests.
/:cl:
> [FIX] Wrong research design icon state

- code/modules/research/designs/tool_designs.dm
- code/modules/surgery/tools.dm
Just makes it so they're found under their actual name in the lathes not whatever else. They don't call it "Advanced Scalpel" anyhow (outside of the fake-alien ones but those are unaffected)
Because people have struggled to find them in the lathe because of the way they're named (Advanced Retractor and Laser Surgical Drill respectively which they aren't even called when you print them)
No.
:cl:
spellcheck: Fixes naming of the Mechanical Pinches and Searing Tool in lathes.
/:cl:
> Renames Pinches and Searing tool designs

- modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
Kinkmate Chem Sell Value Nerf so Cargo doesn't get ban he'd for selling viagra.
Citadel's genital expansion chems sold for a high value, but were easily accessible by buying from a kinkmate.
Cargo abused this, the values are being dropped massively and if there is still further abuse the value can be removed entirely.
The four chems which gave the pills value have been dropped in value from Rare to Common, which is an 80% drop in value.
Nope.
:cl:
balance: Citadel Expansion Chem value reduced.
/:cl:
> Kinkmate Nerf.dm

- code/game/machinery/computer/dna_console.dm
- code/modules/library/lib_items.dm
- tgui/packages/tgui/interfaces/PaperSheet.js
Fix Paper HTML Sanitization and also an important check for DNA Consoles.
Good fixes, ported from TG.
Paper: https://github.com/tgstation/tgstation/pull/65752
DNA Console: https://github.com/tgstation/tgstation/pull/65498
Book Unicode characters compatibility: https://github.com/tgstation/tgstation/pull/56434 (Did not bring over the on_read function, only the Unicode support and extra 10 characters for title)
:cl:
add: Unicode characters compatibility for books. (Write in non-ASCII characters, for example other languages).
fix: Books now showing apostrophes and other characters correctly (They'd break and show &apos, for example).
add: An important sanitization check for the DNA Console.
tweak: Books now have 10 extra characters available for their Title.
/:cl:
> [PORT] [FIX] - Paper and DNA Console sanitization (Apostrophes and other characters now save correctly for books)!

- _maps/splurt_maps/map_files/Smexistation/Snaxi_Splurt.dmm
Fixs the security shutters in Snaxi's warden room, because instead of enclosing all the windows they only closed the top and right hand side windows.
Just fixs and reinforces the warden room incase of emergencies.
No
:cl:
fix: fixs security shutters.
:cl:
> [NON-MODULAR] [READY] Snaxi Security Shutters Fix

- code/datums/elements/flavor_text.dm
- code/modules/client/preferences.dm
See title!
Working headshots.
Nope!
:cl:
tweak: Updates headshot input box to inform on how to make Discord links work.
/:cl:
> [Headshots] Update headshot input box to inform on how to make Discord links work.

- modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
Some alt titles recently introduced in PR 1108 do not fit the lore of SPLURT. This PR aims to fix this.
Because otherwise players will say "Oh I don't respond to CentCom. I respond to the Syndicate. Look at my title." and make people go through hoops.
No.
:cl:
code: Made some chages following PR 1108
/:cl:
> Remove Syndicate Alt Titles

- SpacemanDMM.toml
Manually specifies the environment to use for the langserver.
Fixes the langserver not updating properly until after you recompile.
Nope.
> Fix SpacemanDMM finding the temporary CBT dme

- .gitignore
- code/_compile_options.dm
- code/game/world.dm
Adds support for enabling the Tracy profiler in local testing.
Makes profiling code easier locally, has no effect on the live server.
No, but it uses example code given in https://github.com/mafemergency/byond-tracy.
> Add Tracy profiler support

- code/game/turfs/change_turf.dm
- code/game/turfs/simulated/river.dm
- modular_splurt/code/modules/mapping/lavaland_jungle_gen.dm
Ports a few optimisations and creates a bunch of novel ones, for the purpose of making xenoarch jungle turf generation much, much faster. It went from about 10 seconds to 0.6 seconds. The optimisations also made other things slightly faster as well, resulting in a total init time save of about 14 seconds out of 72 on my machine, or almost 20%.
This does make some relatively invasive changes to ChangeTurf and a few atmos procs, so it MUST be testmerged to ensure nothing is subtly broken. I didn't immediately start suffocating when I spawned in, and lavaland appeared to have the right airmix, but better safe than sorry.
Hopefully shaves about 20% off of init time.
LemonInTheDark was the original one to optimise Spread() by using `CHANGETURF_SKIP`.
> [TESTMERGE THIS!] Dramatically reduce cost of jungle turf generation

- code/datums/status_effects/debuffs.dm
See title!
A one-liner change I had forgotten.
Nope!
:cl:
fix: Sleep now heals instead of dealing damage.
/:cl:
> Fix: sleep dealing damage instead of healing

- code/controllers/subsystem/processing/quirks.dm
- modular_sand/code/controllers/subsystem/processing/quirks.dm
- modular_splurt/code/game/objects/structures/ghost_role_spawners.dm
As title, logs whenever a quirk is cut on a character's spawn due to bad balance / job / species blacklist for admins, and allows the Lavaland hermit ghostrole spawn to load appearance.
Very good!
Noo!
:cl:
qol: Allows Lavaland hermit spawn to load custom character appearance.
/:cl:
> [ADMIN] Roundstart Quirk removal admin log + allows Hermit ghostrole spawn to load custom character

- _maps/map_files/Snaxi/Snaxi.dmm
Fixes an invalid areastring causing linters to fail.
Linters will pass again.
> Fix incorrect EVA storage areastring

- code/modules/research/techweb/nodes/computer_hud_nodes.dm
Adds regular cargo bounty consoles to research because you can't print them otherwise from what I've seen.
Lets you fix em in case the board's gone and also smexy doesn't have any from what I've seen.
No
:cl:
add: Regular bounty console added to research, letting you print it.
/:cl:
> Makes bounty consoles printable

- modular_splurt/code/modules/jobs/job_types/blueshield.dm
Adds one alternate job title for the blueshield: Bluemaid. For all of those blueshield maid enjoyers.
Allows players more freedom in their customization; always nice to have.
Not a port.
:cl:
add: Added a new alternate blueshield job title: Bluemaid.
/:cl:
> Adds One Alternate Job Title For The Blueshield.

- modular_splurt/code/datums/traits/trait_actions.dm
Adds an extra input for the cosmetic glow neutral trait to allow users to change the intensity (alpha) of their glow.
Allows players to further customize their glow POWER. I personally thought the glow was a bit dim, so now everybody can choose their own level of glow.
Not a port.
:cl:
tweak: Allow users with the neutral cosmetic glow trait to change the glow intensity.
/:cl:
> Allow Users To Change Glow Intensity.

- modular_splurt/code/datums/interactions/lewd/lewd_datums.dm
Fixes the thighjobs requiring the person giving it to have a penis but not the one receiving.
Thighfucking itself already exists, this is just a bug.
No.
:cl:
fix: Fixed thighjobs to make the receiver need a penis, not the person giving it.
/:cl:
> Fix thighjobs

- modular_splurt/code/modules/clothing/suits/miscellaneous.dm
Unfucks a line in the code that makes jackets force plantigrade legs on digitigrades. Just a simple pre-vacation fix so I recommend a TM first. Issue also literally only exists on the colored version because the department ones already have the fix.
Fixes my OCD and stuff looking stupid because I was about to remove it from my loadout.
No
:cl:
fix: The colored jackets no longer force plantigrade legs on digitigrades.
/:cl:
> Fix jackets forcing plantigrade legs

- modular_splurt/code/modules/mob/living/emotes.dm
sometimes u dont want to say this mrrmeow, just mrrp. QOL!
makes two emote out of one with two sounds.
sometimes u dont want to say this mrrmeow, just mrrp. QOL!
no
:cl:
qol: mrrp emote rework. Now both sounds have their own emote. (mrrp and mrrp2)
/:cl:
> divide mrrp into mrrp and mrrp2

- code/game/objects/items.dm
It is a fix for the shoes with blood not cleaning even if it is in 'clean' state
Because fixes the blood splatter icon on shoes not be able to be cleaned
No
:cl:
fix: fixed a few things
code: changed some code
/:cl:
> Fixed blood on shoes not cleaning

- code/modules/clothing/under/shorts.dm
Yet another piece of clothing that has no mutantrace style so digi legs get forced into this weird shitty plantigrade style
My OCD and so it doesn't look shit when digitigrade leg people wear it.
No
:cl:
tweak: Fixed digilegs on polychromic workout shorts.
/:cl:
> Poly workout shorts digileg fix

- code/game/world.dm
"Standardises" the hub name entry so that AA07 stops complaining.
> "Standardise" hub name entry so AA07 stops complaining

- code/__DEFINES/is_helpers.dm
- code/game/objects/effects/spawners/gibspawner.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Xenobiological Slime Hybrids are a separate race from Xenobiological Slime Entity, which I believe is because Xenobiological Slime Entity wasn't playable in the past. This change makes it so that Xenobiological Slime Hybrid inherits abilities from Xenobiological Slime Entity.
It allows people that want the body markings from Xenobiological Slime Hybrid to play a proper slime character, plus it's a fix of something unintentional from what I can tell. It's also a simple change so it should merge without any trouble.
Nope.
:cl:
code: replaced all "/datum/species/jelly/roundstartslime" with "/datum/species/jelly/slime/roundstartslime"
code: replaced all "/mob/living/carbon/human/species/roundstartslime" with "/mob/living/carbon/human/species/slime/roundstartslime"
roundstartslime species …
> Quick Xenobiological Slime Hybrid fix

- code/modules/NTNet/network.dm
Fixes a long-standing bug. NTNet transmitters are supposed to be able to transmit to all others, but a single-line bug prevented it.
Being able to send to all other NTNet receivers is a useful thing for making circuits involving many individual parts, and was an originally intended feature.
Fixed this a while ago on the Syndication downstream, with https://github.com/TheSyndication/Syndication/commit/eebe5293bd0232ff47433ac5982024e3efa803dd
This is just a cherry-pick of that commit.
:cl:
fix: NTNet broadcast to all
/:cl:
> Fix bug preventing broadcast to all

- modular_sand/code/game/objects/items/computermath.dm
Fixes a couple bugs with Problem Computers.
Specifically, rounds the expected answer in easy algebra (it stood out as the only not-rounded problem),
and fixes the line intersection problem.
Makes the line intersection problem actually work, instead of being unsolvable. This is a pretty major frustration when using problem computers, since you always have to skip them.
No
:cl:
fix: Rounding in Problem Computer easy algebra
fix: Expected answer in Problem Computer line intersection
refactor: removes duplicated code
/:cl:
> Fix problem computers

- _maps/shuttles/whiteship_meta.dmm
Removes double layered map bug and merge conflict from b8adb77 on meta whiteship
Less bugs
Nope
:cl:
fix: double layered map bug and merge conflict on whiteship for meta
/:cl:
> Fixes mapping bug from b8adb77

- _maps/splurt_maps/map_files/4Nalstation/4NaL_Station.dmm
Fixes something I have no idea how it happened.
:cl:
fix: 4nal tubes
/:cl:
> Immediately, it broke

- modular_splurt/code/game/objects/items/implants/implant_hide_backpack.dm
This PR updates the Chameleon Storage Concealment implant with a few minor features.
- Fake sparks are replaced by telekinesis sparkles
- Spark sound is replaced by a subtle woosh
- Chat messages now indicate what item is worn
- Toggling has a one second cooldown to prevent spam
- No effect or message is generated without a back item
Sparkle effect.
The existing implementation of this implant was designed with placeholder effects that do not adequately represent it. Sparks should not be created by a 'weak psychic signal'. The lack of a cooldown could also lead to unwanted causes of particle effect and sound spam.
No.
:cl:
tweak: Storage Concealment implant uses new SFX
tweak: Storage Concealment implant now has a one-second cooldown
tweak: Storage Concealment implant chat messages now …
> Chameleon Storage Concealment Implant effect rework

- code/modules/mob/living/carbon/human/species_types/ipc.dm
Changes the mutant_bodyparts list in ipc.dm **to include "mam_tail", "mam_ears", "horns"** (_enables tails, ears, horns_);
Modifies hair_alpha on ipc.dm to be set to 255 (full opacity) in order to **fix body parts becoming translucent** (_for some reason_). 
Having extra options for a species = good, in my opinion. The only downside, hair now becomes full opacity on IPCs.
I understand if PR gets closed for this reason, I have not been able to find the tie between hair_alpha and body parts (yet) so this is the best I can do. **Ideally**, hair opacity would be kept the same, while body parts are kept opaque.
Still, I believe the benefit of having extra selectable body parts outweighs the _negligible_ downside of _losing hair translucency_ (previous value 210).
Not a port.
:cl:
tweak: …
> enables tail, horns, ears bodyparts for ipcs; changes ipc hair to opaque

- code/modules/admin/view_variables/debug_variable_appearance.dm
Removes some unnecessary compile-time checks that caused compile errors in byond versions 515.1543 and higher.
Lets people test code without downgrading.
No
:cl:
server: Server can now be compiled on byond 515.1543
/:cl:
> 515.1543 Compatibility

- modular_splurt/code/datums/traits/good.dm
- modular_splurt/code/modules/mob/emote.dm
- tgstation.dme
Title
I better get a dommy mommy for this
No
:cl:
fix: Fixes the snap on dominant aura
/:cl:
> Fixes the dom and sub quirks

- code/modules/events/shuttle_catastrophe.dm
Prevents the shuttle_catastrophe event from occurring when the build your own shuttle is selected.
This was already intended to be the case, but the existing code failed to work due to relying on a name that wasn't actually used. This changes it to check the type instead, since the BYOS has its own subtype.
The build your own shuttle takes a long time to construct well. With the shuttle catastrophe occurring, it undoes hours of work,
and in fact makes it impossible to recover or even restart that work in the same shift. It also has problems on top of that, leading to the shuttle sometimes simply not existing or killing everyone.
Without this, it's practically impossible to make a BYOS that actually works, without an admin disabling events altogether.
Nope.
:cl:
fix: Code disabling the …
> Fix shuttle_catastrophe canSpawnEvent
